(function(){
/*
 Socket.IO v2.1.1
 (c) 2014-2018 Guillermo Rauch
 Released under the MIT License.
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(c){var b=function(){};b.prototype=c;return new b};$jscomp.underscoreProtoCanBeSet=function(){var c={a:!0},b={};try{return b.__proto__=c,b.a}catch(d){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(c,b){c.__proto__=b;if(c.__proto__!==b)throw new TypeError(c+" is not extensible");return c}:null;
$jscomp.inherits=function(c,b){c.prototype=$jscomp.objectCreate(b.prototype);c.prototype.constructor=c;if($jscomp.setPrototypeOf){var d=$jscomp.setPrototypeOf;d(c,b)}else for(d in b)if("prototype"!=d)if(Object.defineProperties){var a=Object.getOwnPropertyDescriptor(b,d);a&&Object.defineProperty(c,d,a)}else c[d]=b[d];c.superClass_=b.prototype};
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(c,b,d){c!=Array.prototype&&c!=Object.prototype&&(c[b]=d.value)};$jscomp.getGlobal=function(c){return"undefined"!=typeof window&&window===c?c:"undefined"!=typeof global&&null!=global?global:c};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.Symbol=function(){var c=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+c++}}();$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var c=$jscomp.global.Symbol.iterator;c||(c=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[c]&&$jscomp.defineProperty(Array.prototype,c,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.arrayIterator=function(c){var b=0;return $jscomp.iteratorPrototype(function(){return b<c.length?{done:!1,value:c[b++]}:{done:!0}})};$jscomp.iteratorPrototype=function(c){$jscomp.initSymbolIterator();c={next:c};c[$jscomp.global.Symbol.iterator]=function(){return this};return c};
$jscomp.iteratorFromArray=function(c,b){$jscomp.initSymbolIterator();c instanceof String&&(c+="");var d=0,a={next:function(){if(d<c.length){var f=d++;return{value:b(f,c[f]),done:!1}}a.next=function(){return{done:!0,value:void 0}};return a.next()}};a[Symbol.iterator]=function(){return a};return a};
$jscomp.polyfill=function(c,b,d,a){if(b){d=$jscomp.global;c=c.split(".");for(a=0;a<c.length-1;a++){var f=c[a];f in d||(d[f]={});d=d[f]}c=c[c.length-1];a=d[c];b=b(a);b!=a&&null!=b&&$jscomp.defineProperty(d,c,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(c){return c?c:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");var module$node_modules$socket_io_client$dist$socket_io_slim={};
module$node_modules$socket_io_client$dist$socket_io_slim["default"]=function(c){function b(a){if(d[a])return d[a].exports;var f=d[a]={exports:{},id:a,loaded:!1};return c[a].call(f.exports,f,f.exports,b),f.loaded=!0,f.exports}var d={};return b.m=c,b.c=d,b.p="",b(0)}([function(c,b,d){function a(a,b){"object"===("undefined"==typeof a?"undefined":f(a))&&(b=a,a=void 0);b=b||{};var d,e=g(a),l=e.source,c=e.id,k=e.path;k=h[c]&&k in h[c].nsps;return b.forceNew||b["force new connection"]||!1===b.multiplex||
k?d=n(l,b):(h[c]||(h[c]=n(l,b)),d=h[c]),e.query&&!b.query&&(b.query=e.query),d.socket(e.path,b)}var f="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},g=d(1),k=d(4),n=d(9);d(3)("socket.io-client");c.exports=b=a;var h=b.managers={};b.protocol=k.protocol;b.connect=a;b.Manager=d(9);b.Socket=d(34)},function(c,b,d){(function(a){var b=d(2);d(3)("socket.io-client:url");
c.exports=function(c,d){var f=c;d=d||a.location;null==c&&(c=d.protocol+"//"+d.host);"string"==typeof c&&("/"===c.charAt(0)&&(c="/"===c.charAt(1)?d.protocol+c:d.host+c),/^(https?|wss?):\/\//.test(c)||(c="undefined"!=typeof d?d.protocol+"//"+c:"https://"+c),f=b(c));f.port||(/^(http|ws)$/.test(f.protocol)?f.port="80":/^(http|ws)s$/.test(f.protocol)&&(f.port="443"));f.path=f.path||"/";var g=-1!==f.host.indexOf(":")?"["+f.host+"]":f.host;return f.id=f.protocol+"://"+g+":"+f.port,f.href=f.protocol+"://"+
g+(d&&d.port===f.port?"":":"+f.port),f}}).call(b,function(){return this}())},function(c,b){var d=/^(?:(?![^:@]+:[^:@\/]*@)(http|https|ws|wss):\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?((?:[a-f0-9]{0,4}:){2,7}[a-f0-9]{0,4}|[^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,a="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");c.exports=function(b){var c=b,f=b.indexOf("["),n=b.indexOf("]");
-1!=f&&-1!=n&&(b=b.substring(0,f)+b.substring(f,n).replace(/:/g,";")+b.substring(n,b.length));b=d.exec(b||"");for(var h={},p=14;p--;)h[a[p]]=b[p]||"";return-1!=f&&-1!=n&&(h.source=c,h.host=h.host.substring(1,h.host.length-1).replace(/;/g,":"),h.authority=h.authority.replace("[","").replace("]","").replace(/;/g,":"),h.ipv6uri=!0),h}},function(c,b){c.exports=function(){return function(){}}},function(c,b,d){function a(){}function f(e){var l=""+e.type;if(b.BINARY_EVENT!==e.type&&b.BINARY_ACK!==e.type||
(l+=e.attachments+"-"),e.nsp&&"/"!==e.nsp&&(l+=e.nsp+","),null!=e.id&&(l+=e.id),null!=e.data){try{var a=JSON.stringify(e.data)}catch(x){a=!1}if(!1===a)return q;l+=a}return l}function g(e,l){h.removeBlobs(e,function(e){var a=h.deconstructPacket(e);e=f(a.packet);a=a.buffers;a.unshift(e);l(a)})}function k(){this.reconstructor=null}function n(e){this.reconPack=e;this.buffers=[]}c=(d(3)("socket.io-parser"),d(5));var h=d(6),p=d(7),m=d(8);b.protocol=4;b.types="CONNECT DISCONNECT EVENT ACK ERROR BINARY_EVENT BINARY_ACK".split(" ");
b.CONNECT=0;b.DISCONNECT=1;b.EVENT=2;b.ACK=3;b.ERROR=4;b.BINARY_EVENT=5;b.BINARY_ACK=6;b.Encoder=a;b.Decoder=k;var q=b.ERROR+'"encode error"';a.prototype.encode=function(e,l){if(b.BINARY_EVENT===e.type||b.BINARY_ACK===e.type)g(e,l);else{var a=f(e);l([a])}};c(k.prototype);k.prototype.add=function(e){if("string"==typeof e){var l=0;var a={type:Number(e.charAt(0))};if(null==b.types[a.type])a={type:b.ERROR,data:"parser error: unknown packet type "+a.type};else{if(b.BINARY_EVENT===a.type||b.BINARY_ACK===
a.type){for(var c="";"-"!==e.charAt(++l)&&(c+=e.charAt(l),l!=e.length););if(c!=Number(c)||"-"!==e.charAt(l))throw Error("Illegal attachments");a.attachments=Number(c)}if("/"===e.charAt(l+1))for(a.nsp="";++l;){c=e.charAt(l);if(","===c)break;if(a.nsp+=c,l===e.length)break}else a.nsp="/";c=e.charAt(l+1);if(""!==c&&Number(c)==c){for(a.id="";++l;){c=e.charAt(l);if(null==c||Number(c)!=c){--l;break}if(a.id+=e.charAt(l),l===e.length)break}a.id=Number(a.id)}if(e.charAt(++l)){e=e.substr(l);try{var d=JSON.parse(e)}catch(v){d=
!1}!1===d||a.type!==b.ERROR&&!p(d)?a={type:b.ERROR,data:"parser error: invalid payload"}:a.data=d}}b.BINARY_EVENT===a.type||b.BINARY_ACK===a.type?(this.reconstructor=new n(a),0===this.reconstructor.reconPack.attachments&&this.emit("decoded",a)):this.emit("decoded",a)}else{if(!m(e)&&!e.base64)throw Error("Unknown type: "+e);if(!this.reconstructor)throw Error("got binary data when not reconstructing a packet");(a=this.reconstructor.takeBinaryData(e))&&(this.reconstructor=null,this.emit("decoded",a))}};
k.prototype.destroy=function(){this.reconstructor&&this.reconstructor.finishedReconstruction()};n.prototype.takeBinaryData=function(a){return(this.buffers.push(a),this.buffers.length===this.reconPack.attachments)?(a=h.reconstructPacket(this.reconPack,this.buffers),this.finishedReconstruction(),a):null};n.prototype.finishedReconstruction=function(){this.reconPack=null;this.buffers=[]}},function(c,b,d){function a(b){if(b){for(var c in a.prototype)b[c]=a.prototype[c];return b}}c.exports=a;a.prototype.on=
a.prototype.addEventListener=function(a,b){return this._callbacks=this._callbacks||{},(this._callbacks["$"+a]=this._callbacks["$"+a]||[]).push(b),this};a.prototype.once=function(a,b){function c(){this.off(a,c);b.apply(this,arguments)}return c.fn=b,this.on(a,c),this};a.prototype.off=a.prototype.removeListener=a.prototype.removeAllListeners=a.prototype.removeEventListener=function(a,b){if(this._callbacks=this._callbacks||{},0==arguments.length)return this._callbacks={},this;var c=this._callbacks["$"+
a];if(!c)return this;if(1==arguments.length)return delete this._callbacks["$"+a],this;for(var d,f=0;f<c.length;f++)if(d=c[f],d===b||d.fn===b){c.splice(f,1);break}return this};a.prototype.emit=function(a){this._callbacks=this._callbacks||{};var b=[].slice.call(arguments,1),c=this._callbacks["$"+a];if(c){c=c.slice(0);for(var d=0,f=c.length;d<f;++d)c[d].apply(this,b)}return this};a.prototype.listeners=function(a){return this._callbacks=this._callbacks||{},this._callbacks["$"+a]||[]};a.prototype.hasListeners=
function(a){return!!this.listeners(a).length}},function(c,b,d){(function(a){function c(a,e){if(!a)return a;if(n(a)){var l={_placeholder:!0,num:e.length};return e.push(a),l}if(k(a)){l=Array(a.length);for(var b=0;b<a.length;b++)l[b]=c(a[b],e);return l}if("object"==typeof a&&!(a instanceof Date)){l={};for(b in a)l[b]=c(a[b],e);return l}return a}function g(a,e){if(!a)return a;if(a&&a._placeholder)return e[a.num];if(k(a))for(var l=0;l<a.length;l++)a[l]=g(a[l],e);else if("object"==typeof a)for(l in a)a[l]=
g(a[l],e);return a}var k=d(7),n=d(8),h=Object.prototype.toString,p="function"==typeof a.Blob||"[object BlobConstructor]"===h.call(a.Blob),m="function"==typeof a.File||"[object FileConstructor]"===h.call(a.File);b.deconstructPacket=function(a){var e=[];return a.data=c(a.data,e),a.attachments=e.length,{packet:a,buffers:e}};b.reconstructPacket=function(a,e){return a.data=g(a.data,e),a.attachments=void 0,a};b.removeBlobs=function(a,e){function l(a,d,f){if(!a)return a;if(p&&a instanceof Blob||m&&a instanceof
File){b++;var g=new FileReader;g.onload=function(){f?f[d]=this.result:c=this.result;--b||e(c)};g.readAsArrayBuffer(a)}else if(k(a))for(g=0;g<a.length;g++)l(a[g],g,a);else if("object"==typeof a&&!n(a))for(g in a)l(a[g],g,a)}var b=0,c=a;l(c);b||e(c)}}).call(b,function(){return this}())},function(c,b){var d={}.toString;c.exports=Array.isArray||function(a){return"[object Array]"==d.call(a)}},function(c,b){(function(b){c.exports=function(c){return a&&b.Buffer.isBuffer(c)||d&&(c instanceof b.ArrayBuffer||
g(c))};var a="function"==typeof b.Buffer&&"function"==typeof b.Buffer.isBuffer,d="function"==typeof b.ArrayBuffer,g=function(){return d&&"function"==typeof b.ArrayBuffer.isView?b.ArrayBuffer.isView:function(a){return a.buffer instanceof b.ArrayBuffer}}()}).call(b,function(){return this}())},function(c,b,d){function a(l,e){if(!(this instanceof a))return new a(l,e);l&&"object"===("undefined"==typeof l?"undefined":f(l))&&(e=l,l=void 0);e=e||{};e.path=e.path||"/socket.io";this.nsps={};this.subs=[];this.opts=
e;this.reconnection(!1!==e.reconnection);this.reconnectionAttempts(e.reconnectionAttempts||1/0);this.reconnectionDelay(e.reconnectionDelay||1E3);this.reconnectionDelayMax(e.reconnectionDelayMax||5E3);this.randomizationFactor(e.randomizationFactor||.5);this.backoff=new q({min:this.reconnectionDelay(),max:this.reconnectionDelayMax(),jitter:this.randomizationFactor()});this.timeout(null==e.timeout?2E4:e.timeout);this.readyState="closed";this.uri=l;this.connecting=[];this.lastPing=null;this.encoding=
!1;this.packetBuffer=[];var b=e.parser||n;this.encoder=new b.Encoder;this.decoder=new b.Decoder;(this.autoConnect=!1!==e.autoConnect)&&this.open()}var f="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},g=d(10),k=d(34);b=d(5);var n=d(4),h=d(36),p=d(37),m=(d(3)("socket.io-client:manager"),d(33)),q=d(38),e=Object.prototype.hasOwnProperty;c.exports=a;
a.prototype.emitAll=function(){this.emit.apply(this,arguments);for(var a in this.nsps)e.call(this.nsps,a)&&this.nsps[a].emit.apply(this.nsps[a],arguments)};a.prototype.updateSocketIds=function(){for(var a in this.nsps)e.call(this.nsps,a)&&(this.nsps[a].id=this.generateId(a))};a.prototype.generateId=function(a){return("/"===a?"":a+"#")+this.engine.id};b(a.prototype);a.prototype.reconnection=function(a){return arguments.length?(this._reconnection=!!a,this):this._reconnection};a.prototype.reconnectionAttempts=
function(a){return arguments.length?(this._reconnectionAttempts=a,this):this._reconnectionAttempts};a.prototype.reconnectionDelay=function(a){return arguments.length?(this._reconnectionDelay=a,this.backoff&&this.backoff.setMin(a),this):this._reconnectionDelay};a.prototype.randomizationFactor=function(a){return arguments.length?(this._randomizationFactor=a,this.backoff&&this.backoff.setJitter(a),this):this._randomizationFactor};a.prototype.reconnectionDelayMax=function(a){return arguments.length?(this._reconnectionDelayMax=
a,this.backoff&&this.backoff.setMax(a),this):this._reconnectionDelayMax};a.prototype.timeout=function(a){return arguments.length?(this._timeout=a,this):this._timeout};a.prototype.maybeReconnectOnOpen=function(){!this.reconnecting&&this._reconnection&&0===this.backoff.attempts&&this.reconnect()};a.prototype.open=a.prototype.connect=function(a,e){if(~this.readyState.indexOf("open"))return this;var b=this.engine=g(this.uri,this.opts),c=this;this.readyState="opening";this.skipReconnect=!1;var l=h(b,"open",
function(){c.onopen();a&&a()}),d=h(b,"error",function(e){if(c.cleanup(),c.readyState="closed",c.emitAll("connect_error",e),a){var b=Error("Connection error");b.data=e;a(b)}else c.maybeReconnectOnOpen()});if(!1!==this._timeout){var f=this._timeout,q=setTimeout(function(){l.destroy();b.close();b.emit("error","timeout");c.emitAll("connect_timeout",f)},f);this.subs.push({destroy:function(){clearTimeout(q)}})}return this.subs.push(l),this.subs.push(d),this};a.prototype.onopen=function(){this.cleanup();
this.readyState="open";this.emit("open");var a=this.engine;this.subs.push(h(a,"data",p(this,"ondata")));this.subs.push(h(a,"ping",p(this,"onping")));this.subs.push(h(a,"pong",p(this,"onpong")));this.subs.push(h(a,"error",p(this,"onerror")));this.subs.push(h(a,"close",p(this,"onclose")));this.subs.push(h(this.decoder,"decoded",p(this,"ondecoded")))};a.prototype.onping=function(){this.lastPing=new Date;this.emitAll("ping")};a.prototype.onpong=function(){this.emitAll("pong",new Date-this.lastPing)};
a.prototype.ondata=function(a){this.decoder.add(a)};a.prototype.ondecoded=function(a){this.emit("packet",a)};a.prototype.onerror=function(a){this.emitAll("error",a)};a.prototype.socket=function(a,e){function b(){~m(l.connecting,c)||l.connecting.push(c)}var c=this.nsps[a];if(!c){c=new k(this,a,e);this.nsps[a]=c;var l=this;c.on("connecting",b);c.on("connect",function(){c.id=l.generateId(a)});this.autoConnect&&b()}return c};a.prototype.destroy=function(a){a=m(this.connecting,a);~a&&this.connecting.splice(a,
1);this.connecting.length||this.close()};a.prototype.packet=function(a){var e=this;a.query&&0===a.type&&(a.nsp+="?"+a.query);e.encoding?e.packetBuffer.push(a):(e.encoding=!0,this.encoder.encode(a,function(b){for(var c=0;c<b.length;c++)e.engine.write(b[c],a.options);e.encoding=!1;e.processPacketQueue()}))};a.prototype.processPacketQueue=function(){if(0<this.packetBuffer.length&&!this.encoding){var a=this.packetBuffer.shift();this.packet(a)}};a.prototype.cleanup=function(){for(var a=this.subs.length,
e=0;e<a;e++)this.subs.shift().destroy();this.packetBuffer=[];this.encoding=!1;this.lastPing=null;this.decoder.destroy()};a.prototype.close=a.prototype.disconnect=function(){this.skipReconnect=!0;this.reconnecting=!1;"opening"===this.readyState&&this.cleanup();this.backoff.reset();this.readyState="closed";this.engine&&this.engine.close()};a.prototype.onclose=function(a){this.cleanup();this.backoff.reset();this.readyState="closed";this.emit("close",a);this._reconnection&&!this.skipReconnect&&this.reconnect()};
a.prototype.reconnect=function(){if(this.reconnecting||this.skipReconnect)return this;var a=this;if(this.backoff.attempts>=this._reconnectionAttempts)this.backoff.reset(),this.emitAll("reconnect_failed"),this.reconnecting=!1;else{var e=this.backoff.duration();this.reconnecting=!0;var b=setTimeout(function(){a.skipReconnect||(a.emitAll("reconnect_attempt",a.backoff.attempts),a.emitAll("reconnecting",a.backoff.attempts),a.skipReconnect||a.open(function(e){e?(a.reconnecting=!1,a.reconnect(),a.emitAll("reconnect_error",
e.data)):a.onreconnect()}))},e);this.subs.push({destroy:function(){clearTimeout(b)}})}};a.prototype.onreconnect=function(){var a=this.backoff.attempts;this.reconnecting=!1;this.backoff.reset();this.updateSocketIds();this.emitAll("reconnect",a)}},function(c,b,d){c.exports=d(11);c.exports.parser=d(18)},function(c,b,d){(function(a){function b(c,e){if(!(this instanceof b))return new b(c,e);e=e||{};c&&"object"==typeof c&&(e=c,c=null);c?(c=p(c),e.hostname=c.host,e.secure="https"===c.protocol||"wss"===c.protocol,
e.port=c.port,c.query&&(e.query=c.query)):e.host&&(e.hostname=p(e.host).host);this.secure=null!=e.secure?e.secure:a.location&&"https:"===location.protocol;e.hostname&&!e.port&&(e.port=this.secure?"443":"80");this.agent=e.agent||!1;this.hostname=e.hostname||(a.location?location.hostname:"localhost");this.port=e.port||(a.location&&location.port?location.port:this.secure?443:80);this.query=e.query||{};"string"==typeof this.query&&(this.query=m.decode(this.query));this.upgrade=!1!==e.upgrade;this.path=
(e.path||"/engine.io").replace(/\/$/,"")+"/";this.forceJSONP=!!e.forceJSONP;this.jsonp=!1!==e.jsonp;this.forceBase64=!!e.forceBase64;this.enablesXDR=!!e.enablesXDR;this.timestampParam=e.timestampParam||"t";this.timestampRequests=e.timestampRequests;this.transports=e.transports||["polling","websocket"];this.transportOptions=e.transportOptions||{};this.readyState="";this.writeBuffer=[];this.prevBufferLen=0;this.policyPort=e.policyPort||843;this.rememberUpgrade=e.rememberUpgrade||!1;this.binaryType=
null;this.onlyBinaryUpgrades=e.onlyBinaryUpgrades;this.perMessageDeflate=!1!==e.perMessageDeflate&&(e.perMessageDeflate||{});!0===this.perMessageDeflate&&(this.perMessageDeflate={});this.perMessageDeflate&&null==this.perMessageDeflate.threshold&&(this.perMessageDeflate.threshold=1024);this.pfx=e.pfx||null;this.key=e.key||null;this.passphrase=e.passphrase||null;this.cert=e.cert||null;this.ca=e.ca||null;this.ciphers=e.ciphers||null;this.rejectUnauthorized=void 0===e.rejectUnauthorized||e.rejectUnauthorized;
this.forceNode=!!e.forceNode;var d="object"==typeof a&&a;d.global===d&&(e.extraHeaders&&0<Object.keys(e.extraHeaders).length&&(this.extraHeaders=e.extraHeaders),e.localAddress&&(this.localAddress=e.localAddress));this.pingTimeoutTimer=this.pingIntervalTimer=this.pingTimeout=this.pingInterval=this.upgrades=this.id=null;this.open()}var g=d(12),k=d(5),n=(d(3)("engine.io-client:socket"),d(33)),h=d(18),p=d(2),m=d(27);c.exports=b;b.priorWebsocketSuccess=!1;k(b.prototype);b.protocol=h.protocol;b.Socket=
b;b.Transport=d(17);b.transports=d(12);b.parser=d(18);b.prototype.createTransport=function(a){var b=this.query,c={},d;for(d in b)b.hasOwnProperty(d)&&(c[d]=b[d]);c.EIO=h.protocol;c.transport=a;b=this.transportOptions[a]||{};this.id&&(c.sid=this.id);return new g[a]({query:c,socket:this,agent:b.agent||this.agent,hostname:b.hostname||this.hostname,port:b.port||this.port,secure:b.secure||this.secure,path:b.path||this.path,forceJSONP:b.forceJSONP||this.forceJSONP,jsonp:b.jsonp||this.jsonp,forceBase64:b.forceBase64||
this.forceBase64,enablesXDR:b.enablesXDR||this.enablesXDR,timestampRequests:b.timestampRequests||this.timestampRequests,timestampParam:b.timestampParam||this.timestampParam,policyPort:b.policyPort||this.policyPort,pfx:b.pfx||this.pfx,key:b.key||this.key,passphrase:b.passphrase||this.passphrase,cert:b.cert||this.cert,ca:b.ca||this.ca,ciphers:b.ciphers||this.ciphers,rejectUnauthorized:b.rejectUnauthorized||this.rejectUnauthorized,perMessageDeflate:b.perMessageDeflate||this.perMessageDeflate,extraHeaders:b.extraHeaders||
this.extraHeaders,forceNode:b.forceNode||this.forceNode,localAddress:b.localAddress||this.localAddress,requestTimeout:b.requestTimeout||this.requestTimeout,protocols:b.protocols||void 0})};b.prototype.open=function(){if(this.rememberUpgrade&&b.priorWebsocketSuccess&&-1!==this.transports.indexOf("websocket"))var a="websocket";else{if(0===this.transports.length){var c=this;return void setTimeout(function(){c.emit("error","No transports available")},0)}a=this.transports[0]}this.readyState="opening";
try{a=this.createTransport(a)}catch(l){return this.transports.shift(),void this.open()}a.open();this.setTransport(a)};b.prototype.setTransport=function(a){var b=this;this.transport&&this.transport.removeAllListeners();this.transport=a;a.on("drain",function(){b.onDrain()}).on("packet",function(a){b.onPacket(a)}).on("error",function(a){b.onError(a)}).on("close",function(){b.onClose("transport close")})};b.prototype.probe=function(a){function c(){if(h.onlyBinaryUpgrades){var a=!this.supportsBinary&&
h.transport.supportsBinary;m=m||a}m||(r.send([{type:"ping",data:"probe"}]),r.once("packet",function(a){if(!m)if("pong"===a.type&&"probe"===a.data){if(h.upgrading=!0,h.emit("upgrading",r),r)b.priorWebsocketSuccess="websocket"===r.name,h.transport.pause(function(){m||"closed"!==h.readyState&&(p(),h.setTransport(r),r.send([{type:"upgrade"}]),h.emit("upgrade",r),r=null,h.upgrading=!1,h.flush())})}else a=Error("probe error"),a.transport=r.name,h.emit("upgradeError",a)}))}function d(){m||(m=!0,p(),r.close(),
r=null)}function f(a){a=Error("probe error: "+a);a.transport=r.name;d();h.emit("upgradeError",a)}function g(){f("transport closed")}function q(){f("socket closed")}function k(a){r&&a.name!==r.name&&d()}function p(){r.removeListener("open",c);r.removeListener("error",f);r.removeListener("close",g);h.removeListener("close",q);h.removeListener("upgrading",k)}var r=this.createTransport(a,{probe:1}),m=!1,h=this;b.priorWebsocketSuccess=!1;r.once("open",c);r.once("error",f);r.once("close",g);this.once("close",
q);this.once("upgrading",k);r.open()};b.prototype.onOpen=function(){if(this.readyState="open",b.priorWebsocketSuccess="websocket"===this.transport.name,this.emit("open"),this.flush(),"open"===this.readyState&&this.upgrade&&this.transport.pause)for(var a=0,c=this.upgrades.length;a<c;a++)this.probe(this.upgrades[a])};b.prototype.onPacket=function(a){if("opening"===this.readyState||"open"===this.readyState||"closing"===this.readyState)switch(this.emit("packet",a),this.emit("heartbeat"),a.type){case "open":this.onHandshake(JSON.parse(a.data));
break;case "pong":this.setPing();this.emit("pong");break;case "error":var b=Error("server error");b.code=a.data;this.onError(b);break;case "message":this.emit("data",a.data),this.emit("message",a.data)}};b.prototype.onHandshake=function(a){this.emit("handshake",a);this.id=a.sid;this.transport.query.sid=a.sid;this.upgrades=this.filterUpgrades(a.upgrades);this.pingInterval=a.pingInterval;this.pingTimeout=a.pingTimeout;this.onOpen();"closed"!==this.readyState&&(this.setPing(),this.removeListener("heartbeat",
this.onHeartbeat),this.on("heartbeat",this.onHeartbeat))};b.prototype.onHeartbeat=function(a){clearTimeout(this.pingTimeoutTimer);var b=this;b.pingTimeoutTimer=setTimeout(function(){"closed"!==b.readyState&&b.onClose("ping timeout")},a||b.pingInterval+b.pingTimeout)};b.prototype.setPing=function(){var a=this;clearTimeout(a.pingIntervalTimer);a.pingIntervalTimer=setTimeout(function(){a.ping();a.onHeartbeat(a.pingTimeout)},a.pingInterval)};b.prototype.ping=function(){var a=this;this.sendPacket("ping",
function(){a.emit("ping")})};b.prototype.onDrain=function(){this.writeBuffer.splice(0,this.prevBufferLen);this.prevBufferLen=0;0===this.writeBuffer.length?this.emit("drain"):this.flush()};b.prototype.flush=function(){"closed"!==this.readyState&&this.transport.writable&&!this.upgrading&&this.writeBuffer.length&&(this.transport.send(this.writeBuffer),this.prevBufferLen=this.writeBuffer.length,this.emit("flush"))};b.prototype.write=b.prototype.send=function(a,b,c){return this.sendPacket("message",a,
b,c),this};b.prototype.sendPacket=function(a,b,c,d){if("function"==typeof b&&(d=b,b=void 0),"function"==typeof c&&(d=c,c=null),"closing"!==this.readyState&&"closed"!==this.readyState)c=c||{},c.compress=!1!==c.compress,a={type:a,data:b,options:c},this.emit("packetCreate",a),this.writeBuffer.push(a),d&&this.once("flush",d),this.flush()};b.prototype.close=function(){function a(){d.onClose("forced close");d.transport.close()}function b(){d.removeListener("upgrade",b);d.removeListener("upgradeError",b);
a()}function c(){d.once("upgrade",b);d.once("upgradeError",b)}if("opening"===this.readyState||"open"===this.readyState){this.readyState="closing";var d=this;this.writeBuffer.length?this.once("drain",function(){this.upgrading?c():a()}):this.upgrading?c():a()}return this};b.prototype.onError=function(a){b.priorWebsocketSuccess=!1;this.emit("error",a);this.onClose("transport error",a)};b.prototype.onClose=function(a,b){if("opening"===this.readyState||"open"===this.readyState||"closing"===this.readyState)clearTimeout(this.pingIntervalTimer),
clearTimeout(this.pingTimeoutTimer),this.transport.removeAllListeners("close"),this.transport.close(),this.transport.removeAllListeners(),this.readyState="closed",this.id=null,this.emit("close",a,b),this.writeBuffer=[],this.prevBufferLen=0};b.prototype.filterUpgrades=function(a){for(var b=[],c=0,d=a.length;c<d;c++)~n(this.transports,a[c])&&b.push(a[c]);return b}}).call(b,function(){return this}())},function(c,b,d){(function(a){var c=d(13),g=d(15),k=d(30),n=d(31);b.polling=function(b){var d,f=!1,h=
!1,e=!1!==b.jsonp;a.location&&(h="https:"===location.protocol,(f=location.port)||(f=h?443:80),f=b.hostname!==location.hostname||f!==b.port,h=b.secure!==h);if(b.xdomain=f,b.xscheme=h,d=new c(b),"open"in d&&!b.forceJSONP)return new g(b);if(!e)throw Error("JSONP disabled");return new k(b)};b.websocket=n}).call(b,function(){return this}())},function(c,b,d){(function(a){var b=d(14);c.exports=function(c){var d=c.xdomain,f=c.xscheme;c=c.enablesXDR;try{if("undefined"!=typeof XMLHttpRequest&&(!d||b))return new XMLHttpRequest}catch(h){}try{if("undefined"!=
typeof XDomainRequest&&!f&&c)return new XDomainRequest}catch(h){}if(!d)try{return new (a[["Active"].concat("Object").join("X")])("Microsoft.XMLHTTP")}catch(h){}}}).call(b,function(){return this}())},function(c,b){try{c.exports="undefined"!=typeof XMLHttpRequest&&"withCredentials"in new XMLHttpRequest}catch(d){c.exports=!1}},function(c,b,d){(function(a){function b(){}function g(b){if(p.call(this,b),this.requestTimeout=b.requestTimeout,this.extraHeaders=b.extraHeaders,a.location){var c="https:"===location.protocol,
d=location.port;d||(d=c?443:80);this.xd=b.hostname!==a.location.hostname||d!==b.port;this.xs=b.secure!==c}}function k(a){this.method=a.method||"GET";this.uri=a.uri;this.xd=!!a.xd;this.xs=!!a.xs;this.async=!1!==a.async;this.data=void 0!==a.data?a.data:null;this.agent=a.agent;this.isBinary=a.isBinary;this.supportsBinary=a.supportsBinary;this.enablesXDR=a.enablesXDR;this.requestTimeout=a.requestTimeout;this.pfx=a.pfx;this.key=a.key;this.passphrase=a.passphrase;this.cert=a.cert;this.ca=a.ca;this.ciphers=
a.ciphers;this.rejectUnauthorized=a.rejectUnauthorized;this.extraHeaders=a.extraHeaders;this.create()}function n(){for(var a in k.requests)k.requests.hasOwnProperty(a)&&k.requests[a].abort()}var h=d(13),p=d(16),m=d(5),q=d(28);d(3)("engine.io-client:polling-xhr");c.exports=g;c.exports.Request=k;q(g,p);g.prototype.supportsBinary=!0;g.prototype.request=function(a){return a=a||{},a.uri=this.uri(),a.xd=this.xd,a.xs=this.xs,a.agent=this.agent||!1,a.supportsBinary=this.supportsBinary,a.enablesXDR=this.enablesXDR,
a.pfx=this.pfx,a.key=this.key,a.passphrase=this.passphrase,a.cert=this.cert,a.ca=this.ca,a.ciphers=this.ciphers,a.rejectUnauthorized=this.rejectUnauthorized,a.requestTimeout=this.requestTimeout,a.extraHeaders=this.extraHeaders,new k(a)};g.prototype.doWrite=function(a,b){var c=this.request({method:"POST",data:a,isBinary:"string"!=typeof a&&void 0!==a}),d=this;c.on("success",b);c.on("error",function(a){d.onError("xhr post error",a)});this.sendXhr=c};g.prototype.doPoll=function(){var a=this.request(),
b=this;a.on("data",function(a){b.onData(a)});a.on("error",function(a){b.onError("xhr poll error",a)});this.pollXhr=a};m(k.prototype);k.prototype.create=function(){var b={agent:this.agent,xdomain:this.xd,xscheme:this.xs,enablesXDR:this.enablesXDR};b.pfx=this.pfx;b.key=this.key;b.passphrase=this.passphrase;b.cert=this.cert;b.ca=this.ca;b.ciphers=this.ciphers;b.rejectUnauthorized=this.rejectUnauthorized;var c=this.xhr=new h(b),d=this;try{c.open(this.method,this.uri,this.async);try{if(this.extraHeaders){c.setDisableHeaderCheck&&
c.setDisableHeaderCheck(!0);for(var f in this.extraHeaders)this.extraHeaders.hasOwnProperty(f)&&c.setRequestHeader(f,this.extraHeaders[f])}}catch(u){}if("POST"===this.method)try{this.isBinary?c.setRequestHeader("Content-type","application/octet-stream"):c.setRequestHeader("Content-type","text/plain;charset=UTF-8")}catch(u){}try{c.setRequestHeader("Accept","*/*")}catch(u){}"withCredentials"in c&&(c.withCredentials=!0);this.requestTimeout&&(c.timeout=this.requestTimeout);this.hasXDR()?(c.onload=function(){d.onLoad()},
c.onerror=function(){d.onError(c.responseText)}):c.onreadystatechange=function(){if(2===c.readyState)try{var a=c.getResponseHeader("Content-Type");d.supportsBinary&&"application/octet-stream"===a&&(c.responseType="arraybuffer")}catch(v){}4===c.readyState&&(200===c.status||1223===c.status?d.onLoad():setTimeout(function(){d.onError(c.status)},0))};c.send(this.data)}catch(u){return void setTimeout(function(){d.onError(u)},0)}a.document&&(this.index=k.requestsCount++,k.requests[this.index]=this)};k.prototype.onSuccess=
function(){this.emit("success");this.cleanup()};k.prototype.onData=function(a){this.emit("data",a);this.onSuccess()};k.prototype.onError=function(a){this.emit("error",a);this.cleanup(!0)};k.prototype.cleanup=function(c){if("undefined"!=typeof this.xhr&&null!==this.xhr){if(this.hasXDR()?this.xhr.onload=this.xhr.onerror=b:this.xhr.onreadystatechange=b,c)try{this.xhr.abort()}catch(l){}a.document&&delete k.requests[this.index];this.xhr=null}};k.prototype.onLoad=function(){try{try{var a=this.xhr.getResponseHeader("Content-Type")}catch(t){}var b=
"application/octet-stream"===a?this.xhr.response||this.xhr.responseText:this.xhr.responseText}catch(t){this.onError(t)}null!=b&&this.onData(b)};k.prototype.hasXDR=function(){return"undefined"!=typeof a.XDomainRequest&&!this.xs&&this.enablesXDR};k.prototype.abort=function(){this.cleanup()};k.requestsCount=0;k.requests={};a.document&&(a.attachEvent?a.attachEvent("onunload",n):a.addEventListener&&a.addEventListener("beforeunload",n,!1))}).call(b,function(){return this}())},function(c,b,d){function a(a){var b=
a&&a.forceBase64;h&&!b||(this.supportsBinary=!1);f.call(this,a)}var f=d(17),g=d(27),k=d(18);b=d(28);var n=d(29);d(3)("engine.io-client:polling");c.exports=a;var h=null!=(new (d(13))({xdomain:!1})).responseType;b(a,f);a.prototype.name="polling";a.prototype.doOpen=function(){this.poll()};a.prototype.pause=function(a){function b(){c.readyState="paused";a()}var c=this;if(this.readyState="pausing",this.polling||!this.writable){var d=0;this.polling&&(d++,this.once("pollComplete",function(){--d||b()}));
this.writable||(d++,this.once("drain",function(){--d||b()}))}else b()};a.prototype.poll=function(){this.polling=!0;this.doPoll();this.emit("poll")};a.prototype.onData=function(a){var b=this;k.decodePayload(a,this.socket.binaryType,function(a,c,d){return"opening"===b.readyState&&b.onOpen(),"close"===a.type?(b.onClose(),!1):void b.onPacket(a)});"closed"!==this.readyState&&(this.polling=!1,this.emit("pollComplete"),"open"===this.readyState&&this.poll())};a.prototype.doClose=function(){function a(){b.write([{type:"close"}])}
var b=this;"open"===this.readyState?a():this.once("open",a)};a.prototype.write=function(a){var b=this;this.writable=!1;var c=function(){b.writable=!0;b.emit("drain")};k.encodePayload(a,this.supportsBinary,function(a){b.doWrite(a,c)})};a.prototype.uri=function(){var a=this.query||{},b=this.secure?"https":"http",c="";!1!==this.timestampRequests&&(a[this.timestampParam]=n());this.supportsBinary||a.sid||(a.b64=1);a=g.encode(a);this.port&&("https"===b&&443!==Number(this.port)||"http"===b&&80!==Number(this.port))&&
(c=":"+this.port);a.length&&(a="?"+a);var d=-1!==this.hostname.indexOf(":");return b+"://"+(d?"["+this.hostname+"]":this.hostname)+c+this.path+a}},function(c,b,d){function a(a){this.path=a.path;this.hostname=a.hostname;this.port=a.port;this.secure=a.secure;this.query=a.query;this.timestampParam=a.timestampParam;this.timestampRequests=a.timestampRequests;this.readyState="";this.agent=a.agent||!1;this.socket=a.socket;this.enablesXDR=a.enablesXDR;this.pfx=a.pfx;this.key=a.key;this.passphrase=a.passphrase;
this.cert=a.cert;this.ca=a.ca;this.ciphers=a.ciphers;this.rejectUnauthorized=a.rejectUnauthorized;this.forceNode=a.forceNode;this.extraHeaders=a.extraHeaders;this.localAddress=a.localAddress}var f=d(18);b=d(5);c.exports=a;b(a.prototype);a.prototype.onError=function(a,b){var c=Error(a);return c.type="TransportError",c.description=b,this.emit("error",c),this};a.prototype.open=function(){return"closed"!==this.readyState&&""!==this.readyState||(this.readyState="opening",this.doOpen()),this};a.prototype.close=
function(){return"opening"!==this.readyState&&"open"!==this.readyState||(this.doClose(),this.onClose()),this};a.prototype.send=function(a){if("open"!==this.readyState)throw Error("Transport not open");this.write(a)};a.prototype.onOpen=function(){this.readyState="open";this.writable=!0;this.emit("open")};a.prototype.onData=function(a){a=f.decodePacket(a,this.socket.binaryType);this.onPacket(a)};a.prototype.onPacket=function(a){this.emit("packet",a)};a.prototype.onClose=function(){this.readyState="closed";
this.emit("close")}},function(c,b,d){(function(a){function c(a,c,d){if(!c)return b.encodeBase64Packet(a,d);var e=new FileReader;return e.onload=function(){a.data=e.result;b.encodePacket(a,c,!0,d)},e.readAsArrayBuffer(a.data)}function g(a,b,c){var d=Array(a.length);c=m(a.length,c);for(var e=function(a,c,e){b(c,function(b,c){d[a]=c;e(b,d)})},f=0;f<a.length;f++)e(f,a[f],c)}var k,n=d(19),h=d(20),p=d(21),m=d(22),q=d(23);a&&a.ArrayBuffer&&(k=d(25));var e="undefined"!=typeof navigator&&/Android/i.test(navigator.userAgent),
l="undefined"!=typeof navigator&&/PhantomJS/i.test(navigator.userAgent),t=e||l;b.protocol=3;var x=b.packets={open:0,close:1,ping:2,pong:3,message:4,upgrade:5,noop:6},u=n(x),v={type:"error",data:"parser error"},w=d(26);b.encodePacket=function(d,e,f,l){"function"==typeof e&&(l=e,e=!1);"function"==typeof f&&(l=f,f=null);var g=void 0===d.data?void 0:d.data.buffer||d.data;if(a.ArrayBuffer&&g instanceof ArrayBuffer){if(e){f=d.data;e=new Uint8Array(f);f=new Uint8Array(1+f.byteLength);f[0]=x[d.type];for(d=
0;d<e.length;d++)f[d+1]=e[d];d=l(f.buffer)}else d=b.encodeBase64Packet(d,l);return d}if(w&&g instanceof a.Blob)return e?t?d=c(d,e,l):(e=new Uint8Array(1),e[0]=x[d.type],d=new w([e.buffer,d.data]),d=l(d)):d=b.encodeBase64Packet(d,l),d;if(g&&g.base64)return l("b"+b.packets[d.type]+d.data.data);e=x[d.type];return void 0!==d.data&&(e+=f?q.encode(String(d.data),{strict:!1}):String(d.data)),l(""+e)};b.encodeBase64Packet=function(c,d){var e="b"+b.packets[c.type];if(w&&c.data instanceof a.Blob){var f=new FileReader;
return f.onload=function(){var a=f.result.split(",")[1];d(e+a)},f.readAsDataURL(c.data)}try{var l=String.fromCharCode.apply(null,new Uint8Array(c.data))}catch(A){l=new Uint8Array(c.data);for(var g=Array(l.length),k=0;k<l.length;k++)g[k]=l[k];l=String.fromCharCode.apply(null,g)}return e+=a.btoa(l),d(e)};b.decodePacket=function(a,c,d){if(void 0===a)return v;if("string"==typeof a){if("b"===a.charAt(0))return b.decodeBase64Packet(a.substr(1),c);if(c=d){c=a;try{c=q.decode(c,{strict:!1})}catch(z){c=!1}c=
(a=c,!1===a)}if(c)return v;d=a.charAt(0);return Number(d)==d&&u[d]?1<a.length?{type:u[d],data:a.substring(1)}:{type:u[d]}:v}d=(new Uint8Array(a))[0];a=p(a,1);return w&&"blob"===c&&(a=new w([a])),{type:u[d],data:a}};b.decodeBase64Packet=function(a,b){var c=u[a.charAt(0)];if(!k)return{type:c,data:{base64:!0,data:a.substr(1)}};var d=k.decode(a.substr(1));return"blob"===b&&w&&(d=new w([d])),{type:c,data:d}};b.encodePayload=function(a,c,d){function e(a,d){b.encodePacket(a,!!f&&c,!1,function(a){d(null,
a.length+":"+a)})}"function"==typeof c&&(d=c,c=null);var f=h(a);return c&&f?w&&!t?b.encodePayloadAsBlob(a,d):b.encodePayloadAsArrayBuffer(a,d):a.length?void g(a,e,function(a,b){return d(b.join(""))}):d("0:")};b.decodePayload=function(a,c,d){if("string"!=typeof a)return b.decodePayloadAsBinary(a,c,d);"function"==typeof c&&(d=c,c=null);var e;if(""===a)return d(v,0,1);for(var f,l,g="",k=0,h=a.length;k<h;k++){var m=a.charAt(k);if(":"===m){if(""===g||g!=(f=Number(g))||(l=a.substr(k+1,f),g!=l.length))return d(v,
0,1);if(l.length){if(e=b.decodePacket(l,c,!1),v.type===e.type&&v.data===e.data)return d(v,0,1);if(!1===d(e,k+f,h))return}k+=f;g=""}else g+=m}return""!==g?d(v,0,1):void 0};b.encodePayloadAsArrayBuffer=function(a,c){function d(a,c){b.encodePacket(a,!0,!0,function(a){return c(null,a)})}return a.length?void g(a,d,function(a,b){var d=b.reduce(function(a,b){var c;return c="string"==typeof b?b.length:b.byteLength,a+c.toString().length+c+2},0),e=new Uint8Array(d),f=0;return b.forEach(function(a){var b="string"==
typeof a,c=a;if(b){c=new Uint8Array(a.length);for(var d=0;d<a.length;d++)c[d]=a.charCodeAt(d);c=c.buffer}b?e[f++]=0:e[f++]=1;a=c.byteLength.toString();for(d=0;d<a.length;d++)e[f++]=parseInt(a[d]);e[f++]=255;c=new Uint8Array(c);for(d=0;d<c.length;d++)e[f++]=c[d]}),c(e.buffer)}):c(new ArrayBuffer(0))};b.encodePayloadAsBlob=function(a,c){g(a,function(a,c){b.encodePacket(a,!0,!0,function(a){var b=new Uint8Array(1);if(b[0]=1,"string"==typeof a){for(var d=new Uint8Array(a.length),e=0;e<a.length;e++)d[e]=
a.charCodeAt(e);a=d.buffer;b[0]=0}d=(a instanceof ArrayBuffer?a.byteLength:a.size).toString();var f=new Uint8Array(d.length+1);for(e=0;e<d.length;e++)f[e]=parseInt(d[e]);if(f[d.length]=255,w)a=new w([b.buffer,f.buffer,a]),c(null,a)})},function(a,b){return c(new w(b))})};b.decodePayloadAsBinary=function(a,c,d){"function"==typeof c&&(d=c,c=null);for(var e=[];0<a.byteLength;){for(var f=new Uint8Array(a),l=0===f[0],g="",k=1;255!==f[k];k++){if(310<g.length)return d(v,0,1);g+=f[k]}a=p(a,2+g.length);g=parseInt(g);
f=p(a,0,g);if(l)try{f=String.fromCharCode.apply(null,new Uint8Array(f))}catch(B){for(l=new Uint8Array(f),f="",k=0;k<l.length;k++)f+=String.fromCharCode(l[k])}e.push(f);a=p(a,g)}var h=e.length;e.forEach(function(a,e){d(b.decodePacket(a,c,!0),e,h)})}}).call(b,function(){return this}())},function(c,b){c.exports=Object.keys||function(b){var a=[],c=Object.prototype.hasOwnProperty,d;for(d in b)c.call(b,d)&&a.push(d);return a}},function(c,b,d){(function(a){function b(c){if(!c||"object"!=typeof c)return!1;
if(g(c)){for(var d=0,f=c.length;d<f;d++)if(b(c[d]))return!0;return!1}if("function"==typeof a.Buffer&&a.Buffer.isBuffer&&a.Buffer.isBuffer(c)||"function"==typeof a.ArrayBuffer&&c instanceof ArrayBuffer||n&&c instanceof Blob||h&&c instanceof File)return!0;if(c.toJSON&&"function"==typeof c.toJSON&&1===arguments.length)return b(c.toJSON(),!0);for(d in c)if(Object.prototype.hasOwnProperty.call(c,d)&&b(c[d]))return!0;return!1}var g=d(7),k=Object.prototype.toString,n="function"==typeof a.Blob||"[object BlobConstructor]"===
k.call(a.Blob),h="function"==typeof a.File||"[object FileConstructor]"===k.call(a.File);c.exports=b}).call(b,function(){return this}())},function(c,b){c.exports=function(b,a,c){var d=b.byteLength;if(a=a||0,c=c||d,b.slice)return b.slice(a,c);if(0>a&&(a+=d),0>c&&(c+=d),c>d&&(c=d),a>=d||a>=c||0===d)return new ArrayBuffer(0);b=new Uint8Array(b);d=new Uint8Array(c-a);for(var f=0;a<c;a++,f++)d[f]=b[a];return d.buffer}},function(c,b){function d(){}c.exports=function(a,b,c){function f(a,d){if(0>=f.count)throw Error("after called too many times");
--f.count;a?(g=!0,b(a),b=c):0!==f.count||g||b(null,d)}var g=!1;return c=c||d,f.count=a,0===a?b():f}},function(c,b,d){var a;(function(c,d){!function(d){function f(a){for(var c,b,d=[],e=0,f=a.length;e<f;)c=a.charCodeAt(e++),55296<=c&&56319>=c&&e<f?(b=a.charCodeAt(e++),56320==(64512&b)?d.push(((1023&c)<<10)+(1023&b)+65536):(d.push(c),e--)):d.push(c);return d}function g(a,c){if(55296<=a&&57343>=a){if(c)throw Error("Lone surrogate U+"+a.toString(16).toUpperCase()+" is not a scalar value");return!1}return!0}
function k(){if(l>=e)throw Error("Invalid byte index");var a=255&q[l];if(l++,128==(192&a))return 63&a;throw Error("Invalid continuation byte");}function m(a){var c,b,d,f,h;if(l>e)throw Error("Invalid byte index");if(l==e)return!1;if(c=255&q[l],l++,0==(128&c))return c;if(192==(224&c)){if(b=k(),h=(31&c)<<6|b,128<=h)return h;throw Error("Invalid continuation byte");}if(224==(240&c)){if(b=k(),d=k(),h=(15&c)<<12|b<<6|d,2048<=h)return g(h,a)?h:65533;throw Error("Invalid continuation byte");}if(240==(248&
c)&&(b=k(),d=k(),f=k(),h=(7&c)<<18|b<<12|d<<6|f,65536<=h&&1114111>=h))return h;throw Error("Invalid UTF-8 detected");}d="object"==typeof b&&b;"object"==typeof c&&c&&c.exports==d&&c;var q,e,l,t=String.fromCharCode;a={version:"2.1.2",encode:function(a,c){c=c||{};for(var b,d=!1!==c.strict,e=f(a),l=e.length,k=-1,h="";++k<l;){b=e[k];var m=d;if(0==(4294967168&b))m=t(b);else{var n="";m=(0==(4294965248&b)?n=t(b>>6&31|192):0==(4294901760&b)?(g(b,m)||(b=65533),n=t(b>>12&15|224),n+=t(b>>6&63|128)):0==(4292870144&
b)&&(n=t(b>>18&7|240),n+=t(b>>12&63|128),n+=t(b>>6&63|128)),n+t(63&b|128))}h+=m}return h},decode:function(a,c){c=c||{};var b=!1!==c.strict;q=f(a);e=q.length;l=0;for(var d,g=[];!1!==(d=m(b));)g.push(d);d=g.length;for(var k=-1,h="";++k<d;)b=g[k],65535<b&&(b-=65536,h+=t(b>>>10&1023|55296),b=56320|1023&b),h+=t(b);return h}};!(void 0!==a&&(c.exports=a))}(this)}).call(b,d(24)(c),function(){return this}())},function(c,b){c.exports=function(b){return b.webpackPolyfill||(b.deprecate=function(){},b.paths=[],
b.children=[],b.webpackPolyfill=1),b}},function(c,b){!function(){for(var c=new Uint8Array(256),a=0;64>a;a++)c["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(a)]=a;b.encode=function(a){var b=new Uint8Array(a),c=b.length,d="";for(a=0;a<c;a+=3)d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[b[a]>>2],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(3&b[a])<<4|b[a+1]>>4],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(15&
b[a+1])<<2|b[a+2]>>6],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[63&b[a+2]];return 2===c%3?d=d.substring(0,d.length-1)+"=":1===c%3&&(d=d.substring(0,d.length-2)+"=="),d};b.decode=function(a){var b=.75*a.length;var d=a.length,f=0;"="===a[a.length-1]&&(b--,"="===a[a.length-2]&&b--);var h=new ArrayBuffer(b),p=new Uint8Array(h);for(b=0;b<d;b+=4){var m=c[a.charCodeAt(b)];var q=c[a.charCodeAt(b+1)];var e=c[a.charCodeAt(b+2)];var l=c[a.charCodeAt(b+3)];p[f++]=m<<2|q>>4;p[f++]=
(15&q)<<4|e>>2;p[f++]=(3&e)<<6|63&l}return h}}()},function(c,b){(function(b){function a(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.buffer instanceof ArrayBuffer){var d=c.buffer;if(c.byteLength!==d.byteLength){var f=new Uint8Array(c.byteLength);f.set(new Uint8Array(d,c.byteOffset,c.byteLength));d=f.buffer}a[b]=d}}}function d(b,c){c=c||{};var d=new k;a(b);for(var f=0;f<b.length;f++)d.append(b[f]);return c.type?d.getBlob(c.type):d.getBlob()}function g(b,c){return a(b),new Blob(b,c||{})}var k=b.BlobBuilder||
b.WebKitBlobBuilder||b.MSBlobBuilder||b.MozBlobBuilder;try{var n=2===(new Blob(["hi"])).size}catch(m){n=!1}var h;if(h=n)try{h=2===(new Blob([new Uint8Array([1,2])])).size}catch(m){h=!1}var p=k&&k.prototype.append&&k.prototype.getBlob;c.exports=n?h?b.Blob:g:p?d:void 0}).call(b,function(){return this}())},function(c,b){b.encode=function(b){var a="",c;for(c in b)b.hasOwnProperty(c)&&(a.length&&(a+="&"),a+=encodeURIComponent(c)+"="+encodeURIComponent(b[c]));return a};b.decode=function(b){var a={};b=b.split("&");
for(var c=0,d=b.length;c<d;c++){var k=b[c].split("=");a[decodeURIComponent(k[0])]=decodeURIComponent(k[1])}return a}},function(c,b){c.exports=function(b,a){var c=function(){};c.prototype=a.prototype;b.prototype=new c;b.prototype.constructor=b}},function(c,b){function d(a){var b="";do b=g[a%k]+b,a=Math.floor(a/k);while(0<a);return b}function a(){var a=d(+new Date);return a!==f?(h=0,f=a):a+"."+d(h++)}for(var f,g="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_".split(""),k=64,n={},
h=0,p=0;p<k;p++)n[g[p]]=p;a.encode=d;a.decode=function(a){var b=0;for(p=0;p<a.length;p++)b=b*k+n[a.charAt(p)];return b};c.exports=a},function(c,b,d){(function(a){function b(){}function g(c){k.call(this,c);this.query=this.query||{};h||(a.___eio||(a.___eio=[]),h=a.___eio);this.index=h.length;var d=this;h.push(function(a){d.onData(a)});this.query.j=this.index;a.document&&a.addEventListener&&a.addEventListener("beforeunload",function(){d.script&&(d.script.onerror=b)},!1)}var k=d(16),n=d(28);c.exports=
g;var h,p=/\n/g,m=/\\n/g;n(g,k);g.prototype.supportsBinary=!1;g.prototype.doClose=function(){this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);this.form&&(this.form.parentNode.removeChild(this.form),this.form=null,this.iframe=null);k.prototype.doClose.call(this)};g.prototype.doPoll=function(){var a=this,b=document.createElement("script");this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);b.async=!0;b.src=this.uri();b.onerror=function(b){a.onError("jsonp poll error",
b)};var c=document.getElementsByTagName("script")[0];c?c.parentNode.insertBefore(b,c):(document.head||document.body).appendChild(b);this.script=b;"undefined"!=typeof navigator&&/gecko/i.test(navigator.userAgent)&&setTimeout(function(){var a=document.createElement("iframe");document.body.appendChild(a);document.body.removeChild(a)},100)};g.prototype.doWrite=function(a,b){function c(){d();b()}function d(){if(e.iframe)try{e.form.removeChild(e.iframe)}catch(y){e.onError("jsonp polling iframe removal error",
y)}try{f=document.createElement('<iframe src="javascript:0" name="'+e.iframeId+'">')}catch(y){f=document.createElement("iframe"),f.name=e.iframeId,f.src="javascript:0"}f.id=e.iframeId;e.form.appendChild(f);e.iframe=f}var e=this;if(!this.form){var f,g=document.createElement("form"),h=document.createElement("textarea"),k=this.iframeId="eio_iframe_"+this.index;g.className="socketio";g.style.position="absolute";g.style.top="-1000px";g.style.left="-1000px";g.target=k;g.method="POST";g.setAttribute("accept-charset",
"utf-8");h.name="d";g.appendChild(h);document.body.appendChild(g);this.form=g;this.area=h}this.form.action=this.uri();d();a=a.replace(m,"\\\n");this.area.value=a.replace(p,"\\n");try{this.form.submit()}catch(y){}this.iframe.attachEvent?this.iframe.onreadystatechange=function(){"complete"===e.iframe.readyState&&c()}:this.iframe.onload=c}}).call(b,function(){return this}())},function(c,b,d){(function(a){function b(a){a&&a.forceBase64&&(this.supportsBinary=!1);this.perMessageDeflate=a.perMessageDeflate;
this.usingBrowserWebSocket=m&&!a.forceNode;this.protocols=a.protocols;this.usingBrowserWebSocket||(e=q);g.call(this,a)}var g=d(17),k=d(18),n=d(27),h=d(28),p=d(29),m=(d(3)("engine.io-client:websocket"),a.WebSocket||a.MozWebSocket);if("undefined"==typeof window)try{var q=d(32)}catch(l){}var e=m;e||"undefined"!=typeof window||(e=q);c.exports=b;h(b,g);b.prototype.name="websocket";b.prototype.supportsBinary=!0;b.prototype.doOpen=function(){if(this.check()){var a=this.uri(),b=this.protocols,c={agent:this.agent,
perMessageDeflate:this.perMessageDeflate};c.pfx=this.pfx;c.key=this.key;c.passphrase=this.passphrase;c.cert=this.cert;c.ca=this.ca;c.ciphers=this.ciphers;c.rejectUnauthorized=this.rejectUnauthorized;this.extraHeaders&&(c.headers=this.extraHeaders);this.localAddress&&(c.localAddress=this.localAddress);try{this.ws=this.usingBrowserWebSocket?b?new e(a,b):new e(a):new e(a,b,c)}catch(u){return this.emit("error",u)}void 0===this.ws.binaryType&&(this.supportsBinary=!1);this.ws.supports&&this.ws.supports.binary?
(this.supportsBinary=!0,this.ws.binaryType="nodebuffer"):this.ws.binaryType="arraybuffer";this.addEventListeners()}};b.prototype.addEventListeners=function(){var a=this;this.ws.onopen=function(){a.onOpen()};this.ws.onclose=function(){a.onClose()};this.ws.onmessage=function(b){a.onData(b.data)};this.ws.onerror=function(b){a.onError("websocket error",b)}};b.prototype.write=function(b){function c(){d.emit("flush");setTimeout(function(){d.writable=!0;d.emit("drain")},0)}var d=this;this.writable=!1;for(var e=
b.length,f=0,l=e;f<l;f++)!function(b){k.encodePacket(b,d.supportsBinary,function(f){if(!d.usingBrowserWebSocket){var l={};(b.options&&(l.compress=b.options.compress),d.perMessageDeflate)&&("string"==typeof f?a.Buffer.byteLength(f):f.length)<d.perMessageDeflate.threshold&&(l.compress=!1)}try{d.usingBrowserWebSocket?d.ws.send(f):d.ws.send(f,l)}catch(z){}--e||c()})}(b[f])};b.prototype.onClose=function(){g.prototype.onClose.call(this)};b.prototype.doClose=function(){"undefined"!=typeof this.ws&&this.ws.close()};
b.prototype.uri=function(){var a=this.query||{},b=this.secure?"wss":"ws",c="";this.port&&("wss"===b&&443!==Number(this.port)||"ws"===b&&80!==Number(this.port))&&(c=":"+this.port);this.timestampRequests&&(a[this.timestampParam]=p());this.supportsBinary||(a.b64=1);a=n.encode(a);a.length&&(a="?"+a);var d=-1!==this.hostname.indexOf(":");return b+"://"+(d?"["+this.hostname+"]":this.hostname)+c+this.path+a};b.prototype.check=function(){return!(!e||"__initialize"in e&&this.name===b.prototype.name)}}).call(b,
function(){return this}())},function(c,b){},function(c,b){var d=[].indexOf;c.exports=function(a,b){if(d)return a.indexOf(b);for(var c=0;c<a.length;++c)if(a[c]===b)return c;return-1}},function(c,b,d){function a(a,b,c){this.io=a;this.nsp=b;this.json=this;this.ids=0;this.acks={};this.receiveBuffer=[];this.sendBuffer=[];this.connected=!1;this.disconnected=!0;this.flags={};c&&c.query&&(this.query=c.query);this.io.autoConnect&&this.open()}var f="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?
function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},g=d(4);b=d(5);var k=d(35),n=d(36),h=d(37),p=(d(3)("socket.io-client:socket"),d(27)),m=d(20);c.exports=a;var q={connect:1,connect_error:1,connect_timeout:1,connecting:1,disconnect:1,error:1,reconnect:1,reconnect_attempt:1,reconnect_failed:1,reconnect_error:1,reconnecting:1,ping:1,pong:1},e=b.prototype.emit;b(a.prototype);a.prototype.subEvents=function(){if(!this.subs){var a=
this.io;this.subs=[n(a,"open",h(this,"onopen")),n(a,"packet",h(this,"onpacket")),n(a,"close",h(this,"onclose"))]}};a.prototype.open=a.prototype.connect=function(){return this.connected?this:(this.subEvents(),this.io.open(),"open"===this.io.readyState&&this.onopen(),this.emit("connecting"),this)};a.prototype.send=function(){var a=k(arguments);return a.unshift("message"),this.emit.apply(this,a),this};a.prototype.emit=function(a){if(q.hasOwnProperty(a))return e.apply(this,arguments),this;var b=k(arguments),
c={type:(void 0!==this.flags.binary?this.flags.binary:m(b))?g.BINARY_EVENT:g.EVENT,data:b};return c.options={},c.options.compress=!this.flags||!1!==this.flags.compress,"function"==typeof b[b.length-1]&&(this.acks[this.ids]=b.pop(),c.id=this.ids++),this.connected?this.packet(c):this.sendBuffer.push(c),this.flags={},this};a.prototype.packet=function(a){a.nsp=this.nsp;this.io.packet(a)};a.prototype.onopen=function(){if("/"!==this.nsp)if(this.query){var a="object"===f(this.query)?p.encode(this.query):
this.query;this.packet({type:g.CONNECT,query:a})}else this.packet({type:g.CONNECT})};a.prototype.onclose=function(a){this.connected=!1;this.disconnected=!0;delete this.id;this.emit("disconnect",a)};a.prototype.onpacket=function(a){var b=a.type===g.ERROR&&"/"===a.nsp;if(a.nsp===this.nsp||b)switch(a.type){case g.CONNECT:this.onconnect();break;case g.EVENT:this.onevent(a);break;case g.BINARY_EVENT:this.onevent(a);break;case g.ACK:this.onack(a);break;case g.BINARY_ACK:this.onack(a);break;case g.DISCONNECT:this.ondisconnect();
break;case g.ERROR:this.emit("error",a.data)}};a.prototype.onevent=function(a){var b=a.data||[];null!=a.id&&b.push(this.ack(a.id));this.connected?e.apply(this,b):this.receiveBuffer.push(b)};a.prototype.ack=function(a){var b=this,c=!1;return function(){if(!c){c=!0;var d=k(arguments);b.packet({type:m(d)?g.BINARY_ACK:g.ACK,id:a,data:d})}}};a.prototype.onack=function(a){var b=this.acks[a.id];"function"==typeof b&&(b.apply(this,a.data),delete this.acks[a.id])};a.prototype.onconnect=function(){this.connected=
!0;this.disconnected=!1;this.emit("connect");this.emitBuffered()};a.prototype.emitBuffered=function(){var a;for(a=0;a<this.receiveBuffer.length;a++)e.apply(this,this.receiveBuffer[a]);this.receiveBuffer=[];for(a=0;a<this.sendBuffer.length;a++)this.packet(this.sendBuffer[a]);this.sendBuffer=[]};a.prototype.ondisconnect=function(){this.destroy();this.onclose("io server disconnect")};a.prototype.destroy=function(){if(this.subs){for(var a=0;a<this.subs.length;a++)this.subs[a].destroy();this.subs=null}this.io.destroy(this)};
a.prototype.close=a.prototype.disconnect=function(){return this.connected&&this.packet({type:g.DISCONNECT}),this.destroy(),this.connected&&this.onclose("io client disconnect"),this};a.prototype.compress=function(a){return this.flags.compress=a,this};a.prototype.binary=function(a){return this.flags.binary=a,this}},function(c,b){c.exports=function(b,a){for(var c=[],d=(a=a||0)||0;d<b.length;d++)c[d-a]=b[d];return c}},function(c,b){c.exports=function(b,a,c){return b.on(a,c),{destroy:function(){b.removeListener(a,
c)}}}},function(c,b){var d=[].slice;c.exports=function(a,b){if("string"==typeof b&&(b=a[b]),"function"!=typeof b)throw Error("bind() requires a function");var c=d.call(arguments,2);return function(){return b.apply(a,c.concat(d.call(arguments)))}}},function(c,b){function d(a){a=a||{};this.ms=a.min||100;this.max=a.max||1E4;this.factor=a.factor||2;this.jitter=0<a.jitter&&1>=a.jitter?a.jitter:0;this.attempts=0}c.exports=d;d.prototype.duration=function(){var a=this.ms*Math.pow(this.factor,this.attempts++);
if(this.jitter){var b=Math.random(),c=Math.floor(b*this.jitter*a);a=0==(1&Math.floor(10*b))?a-c:a+c}return 0|Math.min(a,this.max)};d.prototype.reset=function(){this.attempts=0};d.prototype.setMin=function(a){this.ms=a};d.prototype.setMax=function(a){this.max=a};d.prototype.setJitter=function(a){this.jitter=a}}]);var Input$$module$src$input=function(){var c=this.keys={},b=this.keyCodes={};document.addEventListener("keydown",function(d){c[d.key]=b[d.keyCode]=!0});document.addEventListener("keyup",function(d){c[d.key]=b[d.keyCode]=!1})},module$src$input={};module$src$input.Input=Input$$module$src$input;var io$$module$src$io=module$node_modules$socket_io_client$dist$socket_io_slim["default"],room$$module$src$io=decodeQuery$$module$src$io(window.location.href).room||"default";console.log("room",room$$module$src$io);var connected$$module$src$io=!1,socket$$module$src$io=(0,module$node_modules$socket_io_client$dist$socket_io_slim["default"])("https://ess-server.herokuapp.com/api/little-game/no-persist-open-chat");
socket$$module$src$io.on("connect",function(){socket$$module$src$io.emit("init",{room:"default",nickname:module$src$game.getPlayer().from},function(){console.log("connected");connected$$module$src$io=!0;emit$$module$src$io(module$src$game.getPlayer())})});socket$$module$src$io.on("msg",function(c){console.log("msg",c);module$src$game.sync(c)});socket$$module$src$io.on("disconnect",function(){console.log("disconnected");connected$$module$src$io=!1});
var emit$$module$src$io=function(c){connected$$module$src$io&&(console.log("emit",c),socket$$module$src$io.emit("msg",c))};function decodeQuery$$module$src$io(c){c=c.split("?").slice(-1)[0].split("#")[0];for(var b={},d=c.split("&"),a=0;a<d.length;a++)c=d[a].split("="),b[decodeURIComponent(c[0])]=decodeURIComponent(c[1]);return b}var module$src$io={emit:emit$$module$src$io};var input$$module$src$game=new Input$$module$src$input,map$$module$src$game=[1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1],gravity$$module$src$game=20,platformHeight$$module$src$game=12,mapDim$$module$src$game={width:8,height:6},scale$$module$src$game=100,pDim$$module$src$game={width:20,height:50},otherPlayers$$module$src$game={},canvas$$module$src$game=document.getElementById("platformer-canvas"),ctx$$module$src$game=canvas$$module$src$game.getContext("2d"),
fps$$module$src$game=40,xSpeed$$module$src$game=400,ySpeed$$module$src$game=1,ySpeedClamp$$module$src$game=500,jumpSpeed$$module$src$game=500,interval$$module$src$game=null,renders$$module$src$game=0,started$$module$src$game=!1,player$$module$src$game={pos:{x:30,y:platformHeight$$module$src$game},vy:0,from:Math.random().toString(36),color:"#"+Math.floor(16777215*Math.random()).toString(16)},getPlayer$$module$src$game=function(){return player$$module$src$game},start$$module$src$game=function(){interval$$module$src$game&&
clearInterval(interval$$module$src$game);player$$module$src$game.pos={x:30,y:platformHeight$$module$src$game};player$$module$src$game.vy=0;interval$$module$src$game=setInterval(function(){update$$module$src$game();render$$module$src$game()},1E3/fps$$module$src$game);module$src$io.emit(player$$module$src$game)},stop$$module$src$game=function(){interval$$module$src$game&&clearInterval(interval$$module$src$game)},sync$$module$src$game=function(c){otherPlayers$$module$src$game[c.from]=c},grounded$$module$src$game=
!1,prevGrounded1$$module$src$game=!1,prevGrounded2$$module$src$game=!1,lastX$$module$src$game=player$$module$src$game.pos.x,lastY$$module$src$game=player$$module$src$game.pos.y,update$$module$src$game=function(){if(input$$module$src$game.keys.a||input$$module$src$game.keys.ArrowLeft)player$$module$src$game.pos.x-=xSpeed$$module$src$game/fps$$module$src$game;if(input$$module$src$game.keys.d||input$$module$src$game.keys.ArrowRight)player$$module$src$game.pos.x+=xSpeed$$module$src$game/fps$$module$src$game;
var c=!1;player$$module$src$game.vy-=gravity$$module$src$game;player$$module$src$game.pos.y+=ySpeed$$module$src$game/fps$$module$src$game*player$$module$src$game.vy;var b=Math.floor(player$$module$src$game.pos.x/scale$$module$src$game),d=Math.floor((player$$module$src$game.pos.x+pDim$$module$src$game.width)/scale$$module$src$game),a=mapDim$$module$src$game.height-Math.floor(player$$module$src$game.pos.y/scale$$module$src$game)-1;(map$$module$src$game[a*mapDim$$module$src$game.width+b]||map$$module$src$game[a*
mapDim$$module$src$game.width+d])&&player$$module$src$game.pos.y%scale$$module$src$game<platformHeight$$module$src$game?(c=!0,player$$module$src$game.vy=0,player$$module$src$game.pos.y=Math.floor(player$$module$src$game.pos.y/scale$$module$src$game)*scale$$module$src$game+platformHeight$$module$src$game):(map$$module$src$game[(a-1)*mapDim$$module$src$game.width+b]||map$$module$src$game[(a-1)*mapDim$$module$src$game.width+d])&&player$$module$src$game.pos.y%scale$$module$src$game>scale$$module$src$game-
pDim$$module$src$game.height&&(!map$$module$src$game[(a-1)*mapDim$$module$src$game.width+b]&&map$$module$src$game[(a-1)*mapDim$$module$src$game.width+d]?player$$module$src$game.pos.x=b*scale$$module$src$game+scale$$module$src$game-pDim$$module$src$game.width-1E-6:map$$module$src$game[(a-1)*mapDim$$module$src$game.width+b]&&!map$$module$src$game[(a-1)*mapDim$$module$src$game.width+d]?player$$module$src$game.pos.x=b*scale$$module$src$game+scale$$module$src$game:(player$$module$src$game.vy=-Math.abs(player$$module$src$game.vy),
player$$module$src$game.pos.y=Math.floor(player$$module$src$game.pos.y/scale$$module$src$game)*scale$$module$src$game+scale$$module$src$game-pDim$$module$src$game.height));input$$module$src$game.keys[" "]&&(c||prevGrounded1$$module$src$game||prevGrounded2$$module$src$game)&&(player$$module$src$game.vy+=jumpSpeed$$module$src$game);player$$module$src$game.vy=Math.min(ySpeedClamp$$module$src$game,Math.max(-ySpeedClamp$$module$src$game,player$$module$src$game.vy));player$$module$src$game.pos.x=Math.min(mapDim$$module$src$game.width*
scale$$module$src$game-pDim$$module$src$game.width,Math.max(0,player$$module$src$game.pos.x));prevGrounded2$$module$src$game=prevGrounded1$$module$src$game=c;if(player$$module$src$game.pos.x!==lastX$$module$src$game||player$$module$src$game.pos.y!==lastY$$module$src$game)started$$module$src$game=!0,module$src$io.emit(player$$module$src$game);lastX$$module$src$game=player$$module$src$game.pos.x;lastY$$module$src$game=player$$module$src$game.pos.y},render$$module$src$game=function(){ctx$$module$src$game.clearRect(0,
0,mapDim$$module$src$game.width*scale$$module$src$game,mapDim$$module$src$game.height*scale$$module$src$game);1E3>renders$$module$src$game&&(ctx$$module$src$game.save(),ctx$$module$src$game.beginPath(),ctx$$module$src$game.arc(player$$module$src$game.pos.x+.5*pDim$$module$src$game.width,mapDim$$module$src$game.height*scale$$module$src$game-player$$module$src$game.pos.y-.5*pDim$$module$src$game.height,renders$$module$src$game+100,0,2*Math.PI,!1),ctx$$module$src$game.clip());ctx$$module$src$game.fillStyle=
"#333";for(var c=0;c<map$$module$src$game.length;c++){var b=c%mapDim$$module$src$game.width,d=Math.floor(c/mapDim$$module$src$game.width);map$$module$src$game[c]&&ctx$$module$src$game.fillRect(b*scale$$module$src$game,d*scale$$module$src$game+scale$$module$src$game-platformHeight$$module$src$game,scale$$module$src$game,platformHeight$$module$src$game)}for(var a in otherPlayers$$module$src$game)c=otherPlayers$$module$src$game[a],ctx$$module$src$game.fillStyle=c.color,ctx$$module$src$game.fillRect(c.pos.x,
mapDim$$module$src$game.height*scale$$module$src$game-c.pos.y-pDim$$module$src$game.height,pDim$$module$src$game.width,pDim$$module$src$game.height);ctx$$module$src$game.fillStyle=player$$module$src$game.color;ctx$$module$src$game.fillRect(player$$module$src$game.pos.x,mapDim$$module$src$game.height*scale$$module$src$game-player$$module$src$game.pos.y-pDim$$module$src$game.height,pDim$$module$src$game.width,pDim$$module$src$game.height);1E3>renders$$module$src$game&&(started$$module$src$game&&(renders$$module$src$game+=
5),ctx$$module$src$game.restore(),started$$module$src$game||(ctx$$module$src$game.font="bold 60px Verdana",ctx$$module$src$game.fillText("Use the keyboard",50,250),ctx$$module$src$game.fillText("to play the game",60,330)))},module$src$game={getPlayer:getPlayer$$module$src$game,start:start$$module$src$game,stop:stop$$module$src$game,sync:sync$$module$src$game};var Heap$$module$src$heaptree=function(){this.items=[]};Heap$$module$src$heaptree.prototype.seek=function(){return this.items[0]};var MaxHeap$$module$src$heaptree=function(c){Heap$$module$src$heaptree.call(this);this.selector=c};$jscomp.inherits(MaxHeap$$module$src$heaptree,Heap$$module$src$heaptree);
MaxHeap$$module$src$heaptree.prototype.push=function(c){var b=this.items.length;for(this.items.push(c);0<b&&this.selector(this.items[Math.floor((b+1)/2-1)])<this.selector(this.items[b]);)c=this.items[b],this.items[b]=this.items[Math.floor((b+1)/2-1)],this.items[Math.floor((b+1)/2-1)]=c,b=Math.floor((b+1)/2-1)};
MaxHeap$$module$src$heaptree.prototype.pop=function(){if(1>=this.items.length)return this.items.pop();var c=this.items[0];this.items[0]=this.items.pop();for(var b=0;;){var d=this.selector(this.items[2*(b+1)])>this.selector(this.items[2*(b+1)-1])?2*(b+1):2*(b+1)-1;if(this.selector(this.items[b])<this.selector(this.items[d])){var a=this.items[b];this.items[b]=this.items[d];this.items[d]=a;b=d}else break}return c};
MaxHeap$$module$src$heaptree.prototype["delete"]=function(c){c=this.items.indexOf(c);for(this.items[c]=this.items.pop();;){var b=this.selector(this.items[2*(c+1)])>this.selector(this.items[2*(c+1)-1])?2*(c+1):2*(c+1)-1;if(this.selector(this.items[c])<this.selector(this.items[b])){var d=this.items[c];this.items[c]=this.items[b];this.items[b]=d;c=b}else break}};MaxHeap$$module$src$heaptree.prototype.heapify=function(c){for(var b=0;b<c.length;b++)this.push(c[b])};
var MinHeap$$module$src$heaptree=function(c){Heap$$module$src$heaptree.call(this);this.selector=c};$jscomp.inherits(MinHeap$$module$src$heaptree,Heap$$module$src$heaptree);MinHeap$$module$src$heaptree.prototype.push=function(c){var b=this.items.length;for(this.items.push(c);0<b&&this.selector(this.items[Math.floor((b+1)/2-1)])>this.selector(this.items[b]);)c=this.items[b],this.items[b]=this.items[Math.floor((b+1)/2-1)],this.items[Math.floor((b+1)/2-1)]=c,b=Math.floor((b+1)/2-1)};
MinHeap$$module$src$heaptree.prototype.pop=function(){if(1>=this.items.length)return this.items.pop();var c=this.items[0];this.items[0]=this.items.pop();for(var b=0;;){var d=this.selector(this.items[2*(b+1)])<this.selector(this.items[2*(b+1)-1])?2*(b+1):2*(b+1)-1;if(this.selector(this.items[b])>this.selector(this.items[d])){var a=this.items[b];this.items[b]=this.items[d];this.items[d]=a;b=d}else break}return c};
MinHeap$$module$src$heaptree.prototype["delete"]=function(c){c=this.items.indexOf(c);for(this.items[c]=this.items.pop();;){var b=this.selector(this.items[2*(c+1)])<this.selector(this.items[2*(c+1)-1])?2*(c+1):2*(c+1)-1;if(this.selector(this.items[c])>this.selector(this.items[b])){var d=this.items[c];this.items[c]=this.items[b];this.items[b]=d;c=b}else break}};MinHeap$$module$src$heaptree.prototype.heapify=function(c){for(var b=0;b<c.length;b++)this.push(c[b])};var module$src$heaptree={};
module$src$heaptree.MaxHeap=MaxHeap$$module$src$heaptree;module$src$heaptree.MinHeap=MinHeap$$module$src$heaptree;module$src$game.start();var module$src$index={};var GridPath$$module$src$pathfinding=function(c,b){this.width=c;this.height=b;this.len=c*b;this.goalI=this.startI=null};
GridPath$$module$src$pathfinding.prototype.find=function(c,b,d){this.startI=c;this.goalI=b;var a={},f={},g={};g[c]=0;var k={},n=new MinHeap$$module$src$heaptree(function(a){return k[a]||Infinity});k[c]=this.heuristicCostEstimateSquared(c,b);for(n.push(c);0<n.items.length;){c=n.pop();if(c===b)return this.reconstructPath(f,c);a[c]=!0;for(var h=this.neighboursI(c),p=0;p<h.length;p++){var m=h[p];if(!(0>m||m>this.len||a[m]||d&&!d(m))){var q=g[c]+1;k[m]?q>=g[m]||(f[m]=c,g[m]=q,k[m]=q+this.heuristicCostEstimateSquared(m,
b),n["delete"](m),n.push(m)):(f[m]=c,g[m]=q,k[m]=q+this.heuristicCostEstimateSquared(m,b),n.push(m))}}}};GridPath$$module$src$pathfinding.prototype.reconstructPath=function(c,b){var d=0,a=[];for(a.push(b);b!==this.startI;)if(a.push(b),b=c[b],999999<d++)return null;a.push(this.startI);d=Array(a.length);for(var f=0;f<a.length;f++)d[f]=a[a.length-1-f];return d};GridPath$$module$src$pathfinding.prototype.neighboursI=function(c){return[c-this.width,c+1,c+this.width,c-1]};
GridPath$$module$src$pathfinding.prototype.heuristicCostEstimateSquared=function(c,b){return Math.pow(b%this.width-c%this.width,2)+Math.pow(Math.floor(b/this.width)-Math.floor(c/this.width),2)};var module$src$pathfinding={};module$src$pathfinding.GridPath=GridPath$$module$src$pathfinding;
}).call(this)
