(function(){
/*
 Socket.IO v2.1.1
 (c) 2014-2018 Guillermo Rauch
 Released under the MIT License.
*/
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.objectCreate=$jscomp.ASSUME_ES5||"function"==typeof Object.create?Object.create:function(d){var b=function(){};b.prototype=d;return new b};$jscomp.underscoreProtoCanBeSet=function(){var d={a:!0},b={};try{return b.__proto__=d,b.a}catch(c){}return!1};
$jscomp.setPrototypeOf="function"==typeof Object.setPrototypeOf?Object.setPrototypeOf:$jscomp.underscoreProtoCanBeSet()?function(d,b){d.__proto__=b;if(d.__proto__!==b)throw new TypeError(d+" is not extensible");return d}:null;
$jscomp.inherits=function(d,b){d.prototype=$jscomp.objectCreate(b.prototype);d.prototype.constructor=d;if($jscomp.setPrototypeOf){var c=$jscomp.setPrototypeOf;c(d,b)}else for(c in b)if("prototype"!=c)if(Object.defineProperties){var a=Object.getOwnPropertyDescriptor(b,c);a&&Object.defineProperty(d,c,a)}else d[c]=b[c];d.superClass_=b.prototype};
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(d,b,c){d!=Array.prototype&&d!=Object.prototype&&(d[b]=c.value)};$jscomp.getGlobal=function(d){return"undefined"!=typeof window&&window===d?d:"undefined"!=typeof global&&null!=global?global:d};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.Symbol=function(){var d=0;return function(b){return $jscomp.SYMBOL_PREFIX+(b||"")+d++}}();$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var d=$jscomp.global.Symbol.iterator;d||(d=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[d]&&$jscomp.defineProperty(Array.prototype,d,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};
$jscomp.arrayIterator=function(d){var b=0;return $jscomp.iteratorPrototype(function(){return b<d.length?{done:!1,value:d[b++]}:{done:!0}})};$jscomp.iteratorPrototype=function(d){$jscomp.initSymbolIterator();d={next:d};d[$jscomp.global.Symbol.iterator]=function(){return this};return d};
$jscomp.iteratorFromArray=function(d,b){$jscomp.initSymbolIterator();d instanceof String&&(d+="");var c=0,a={next:function(){if(c<d.length){var f=c++;return{value:b(f,d[f]),done:!1}}a.next=function(){return{done:!0,value:void 0}};return a.next()}};a[Symbol.iterator]=function(){return a};return a};
$jscomp.polyfill=function(d,b,c,a){if(b){c=$jscomp.global;d=d.split(".");for(a=0;a<d.length-1;a++){var f=d[a];f in c||(c[f]={});c=c[f]}d=d[d.length-1];a=c[d];b=b(a);b!=a&&null!=b&&$jscomp.defineProperty(c,d,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.keys",function(d){return d?d:function(){return $jscomp.iteratorFromArray(this,function(b){return b})}},"es6","es3");var module$node_modules$socket_io_client$dist$socket_io_slim={};
module$node_modules$socket_io_client$dist$socket_io_slim["default"]=function(d){function b(a){if(c[a])return c[a].exports;var f=c[a]={exports:{},id:a,loaded:!1};return d[a].call(f.exports,f,f.exports,b),f.loaded=!0,f.exports}var c={};return b.m=d,b.c=c,b.p="",b(0)}([function(d,b,c){function a(a,b){"object"===("undefined"==typeof a?"undefined":f(a))&&(b=a,a=void 0);b=b||{};var c,e=h(a),g=e.source,d=e.id,k=e.path;k=l[d]&&k in l[d].nsps;return b.forceNew||b["force new connection"]||!1===b.multiplex||
k?c=n(g,b):(l[d]||(l[d]=n(g,b)),c=l[d]),e.query&&!b.query&&(b.query=e.query),c.socket(e.path,b)}var f="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},h=c(1),k=c(4),n=c(9);c(3)("socket.io-client");d.exports=b=a;var l=b.managers={};b.protocol=k.protocol;b.connect=a;b.Manager=c(9);b.Socket=c(34)},function(d,b,c){(function(a){var b=c(2);c(3)("socket.io-client:url");
d.exports=function(c,d){var f=c;d=d||a.location;null==c&&(c=d.protocol+"//"+d.host);"string"==typeof c&&("/"===c.charAt(0)&&(c="/"===c.charAt(1)?d.protocol+c:d.host+c),/^(https?|wss?):\/\//.test(c)||(c="undefined"!=typeof d?d.protocol+"//"+c:"https://"+c),f=b(c));f.port||(/^(http|ws)$/.test(f.protocol)?f.port="80":/^(http|ws)s$/.test(f.protocol)&&(f.port="443"));f.path=f.path||"/";var h=-1!==f.host.indexOf(":")?"["+f.host+"]":f.host;return f.id=f.protocol+"://"+h+":"+f.port,f.href=f.protocol+"://"+
h+(d&&d.port===f.port?"":":"+f.port),f}}).call(b,function(){return this}())},function(d,b){var c=/^(?:(?![^:@]+:[^:@\/]*@)(http|https|ws|wss):\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?((?:[a-f0-9]{0,4}:){2,7}[a-f0-9]{0,4}|[^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,a="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");d.exports=function(b){var d=b,f=b.indexOf("["),n=b.indexOf("]");
-1!=f&&-1!=n&&(b=b.substring(0,f)+b.substring(f,n).replace(/:/g,";")+b.substring(n,b.length));b=c.exec(b||"");for(var l={},p=14;p--;)l[a[p]]=b[p]||"";return-1!=f&&-1!=n&&(l.source=d,l.host=l.host.substring(1,l.host.length-1).replace(/;/g,":"),l.authority=l.authority.replace("[","").replace("]","").replace(/;/g,":"),l.ipv6uri=!0),l}},function(d,b){d.exports=function(){return function(){}}},function(d,b,c){function a(){}function f(e){var g=""+e.type;if(b.BINARY_EVENT!==e.type&&b.BINARY_ACK!==e.type||
(g+=e.attachments+"-"),e.nsp&&"/"!==e.nsp&&(g+=e.nsp+","),null!=e.id&&(g+=e.id),null!=e.data){try{var a=JSON.stringify(e.data)}catch(x){a=!1}if(!1===a)return q;g+=a}return g}function h(e,g){l.removeBlobs(e,function(e){var a=l.deconstructPacket(e);e=f(a.packet);a=a.buffers;a.unshift(e);g(a)})}function k(){this.reconstructor=null}function n(e){this.reconPack=e;this.buffers=[]}d=(c(3)("socket.io-parser"),c(5));var l=c(6),p=c(7),m=c(8);b.protocol=4;b.types="CONNECT DISCONNECT EVENT ACK ERROR BINARY_EVENT BINARY_ACK".split(" ");
b.CONNECT=0;b.DISCONNECT=1;b.EVENT=2;b.ACK=3;b.ERROR=4;b.BINARY_EVENT=5;b.BINARY_ACK=6;b.Encoder=a;b.Decoder=k;var q=b.ERROR+'"encode error"';a.prototype.encode=function(e,g){if(b.BINARY_EVENT===e.type||b.BINARY_ACK===e.type)h(e,g);else{var a=f(e);g([a])}};d(k.prototype);k.prototype.add=function(e){if("string"==typeof e){var g=0;var a={type:Number(e.charAt(0))};if(null==b.types[a.type])a={type:b.ERROR,data:"parser error: unknown packet type "+a.type};else{if(b.BINARY_EVENT===a.type||b.BINARY_ACK===
a.type){for(var c="";"-"!==e.charAt(++g)&&(c+=e.charAt(g),g!=e.length););if(c!=Number(c)||"-"!==e.charAt(g))throw Error("Illegal attachments");a.attachments=Number(c)}if("/"===e.charAt(g+1))for(a.nsp="";++g;){c=e.charAt(g);if(","===c)break;if(a.nsp+=c,g===e.length)break}else a.nsp="/";c=e.charAt(g+1);if(""!==c&&Number(c)==c){for(a.id="";++g;){c=e.charAt(g);if(null==c||Number(c)!=c){--g;break}if(a.id+=e.charAt(g),g===e.length)break}a.id=Number(a.id)}if(e.charAt(++g)){e=e.substr(g);try{var d=JSON.parse(e)}catch(v){d=
!1}!1===d||a.type!==b.ERROR&&!p(d)?a={type:b.ERROR,data:"parser error: invalid payload"}:a.data=d}}b.BINARY_EVENT===a.type||b.BINARY_ACK===a.type?(this.reconstructor=new n(a),0===this.reconstructor.reconPack.attachments&&this.emit("decoded",a)):this.emit("decoded",a)}else{if(!m(e)&&!e.base64)throw Error("Unknown type: "+e);if(!this.reconstructor)throw Error("got binary data when not reconstructing a packet");(a=this.reconstructor.takeBinaryData(e))&&(this.reconstructor=null,this.emit("decoded",a))}};
k.prototype.destroy=function(){this.reconstructor&&this.reconstructor.finishedReconstruction()};n.prototype.takeBinaryData=function(a){return(this.buffers.push(a),this.buffers.length===this.reconPack.attachments)?(a=l.reconstructPacket(this.reconPack,this.buffers),this.finishedReconstruction(),a):null};n.prototype.finishedReconstruction=function(){this.reconPack=null;this.buffers=[]}},function(d,b,c){function a(b){if(b){for(var c in a.prototype)b[c]=a.prototype[c];return b}}d.exports=a;a.prototype.on=
a.prototype.addEventListener=function(a,b){return this._callbacks=this._callbacks||{},(this._callbacks["$"+a]=this._callbacks["$"+a]||[]).push(b),this};a.prototype.once=function(a,b){function c(){this.off(a,c);b.apply(this,arguments)}return c.fn=b,this.on(a,c),this};a.prototype.off=a.prototype.removeListener=a.prototype.removeAllListeners=a.prototype.removeEventListener=function(a,b){if(this._callbacks=this._callbacks||{},0==arguments.length)return this._callbacks={},this;var c=this._callbacks["$"+
a];if(!c)return this;if(1==arguments.length)return delete this._callbacks["$"+a],this;for(var d,f=0;f<c.length;f++)if(d=c[f],d===b||d.fn===b){c.splice(f,1);break}return this};a.prototype.emit=function(a){this._callbacks=this._callbacks||{};var b=[].slice.call(arguments,1),c=this._callbacks["$"+a];if(c){c=c.slice(0);for(var d=0,f=c.length;d<f;++d)c[d].apply(this,b)}return this};a.prototype.listeners=function(a){return this._callbacks=this._callbacks||{},this._callbacks["$"+a]||[]};a.prototype.hasListeners=
function(a){return!!this.listeners(a).length}},function(d,b,c){(function(a){function d(a,e){if(!a)return a;if(n(a)){var g={_placeholder:!0,num:e.length};return e.push(a),g}if(k(a)){g=Array(a.length);for(var c=0;c<a.length;c++)g[c]=d(a[c],e);return g}if("object"==typeof a&&!(a instanceof Date)){g={};for(c in a)g[c]=d(a[c],e);return g}return a}function h(a,e){if(!a)return a;if(a&&a._placeholder)return e[a.num];if(k(a))for(var g=0;g<a.length;g++)a[g]=h(a[g],e);else if("object"==typeof a)for(g in a)a[g]=
h(a[g],e);return a}var k=c(7),n=c(8),l=Object.prototype.toString,p="function"==typeof a.Blob||"[object BlobConstructor]"===l.call(a.Blob),m="function"==typeof a.File||"[object FileConstructor]"===l.call(a.File);b.deconstructPacket=function(a){var e=[];return a.data=d(a.data,e),a.attachments=e.length,{packet:a,buffers:e}};b.reconstructPacket=function(a,e){return a.data=h(a.data,e),a.attachments=void 0,a};b.removeBlobs=function(a,e){function g(a,d,f){if(!a)return a;if(p&&a instanceof Blob||m&&a instanceof
File){c++;var h=new FileReader;h.onload=function(){f?f[d]=this.result:b=this.result;--c||e(b)};h.readAsArrayBuffer(a)}else if(k(a))for(h=0;h<a.length;h++)g(a[h],h,a);else if("object"==typeof a&&!n(a))for(h in a)g(a[h],h,a)}var c=0,b=a;g(b);c||e(b)}}).call(b,function(){return this}())},function(d,b){var c={}.toString;d.exports=Array.isArray||function(a){return"[object Array]"==c.call(a)}},function(d,b){(function(c){d.exports=function(d){return a&&c.Buffer.isBuffer(d)||b&&(d instanceof c.ArrayBuffer||
h(d))};var a="function"==typeof c.Buffer&&"function"==typeof c.Buffer.isBuffer,b="function"==typeof c.ArrayBuffer,h=function(){return b&&"function"==typeof c.ArrayBuffer.isView?c.ArrayBuffer.isView:function(a){return a.buffer instanceof c.ArrayBuffer}}()}).call(b,function(){return this}())},function(d,b,c){function a(g,e){if(!(this instanceof a))return new a(g,e);g&&"object"===("undefined"==typeof g?"undefined":f(g))&&(e=g,g=void 0);e=e||{};e.path=e.path||"/socket.io";this.nsps={};this.subs=[];this.opts=
e;this.reconnection(!1!==e.reconnection);this.reconnectionAttempts(e.reconnectionAttempts||1/0);this.reconnectionDelay(e.reconnectionDelay||1E3);this.reconnectionDelayMax(e.reconnectionDelayMax||5E3);this.randomizationFactor(e.randomizationFactor||.5);this.backoff=new q({min:this.reconnectionDelay(),max:this.reconnectionDelayMax(),jitter:this.randomizationFactor()});this.timeout(null==e.timeout?2E4:e.timeout);this.readyState="closed";this.uri=g;this.connecting=[];this.lastPing=null;this.encoding=
!1;this.packetBuffer=[];var c=e.parser||n;this.encoder=new c.Encoder;this.decoder=new c.Decoder;(this.autoConnect=!1!==e.autoConnect)&&this.open()}var f="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},h=c(10),k=c(34);b=c(5);var n=c(4),l=c(36),p=c(37),m=(c(3)("socket.io-client:manager"),c(33)),q=c(38),e=Object.prototype.hasOwnProperty;d.exports=a;
a.prototype.emitAll=function(){this.emit.apply(this,arguments);for(var a in this.nsps)e.call(this.nsps,a)&&this.nsps[a].emit.apply(this.nsps[a],arguments)};a.prototype.updateSocketIds=function(){for(var a in this.nsps)e.call(this.nsps,a)&&(this.nsps[a].id=this.generateId(a))};a.prototype.generateId=function(a){return("/"===a?"":a+"#")+this.engine.id};b(a.prototype);a.prototype.reconnection=function(a){return arguments.length?(this._reconnection=!!a,this):this._reconnection};a.prototype.reconnectionAttempts=
function(a){return arguments.length?(this._reconnectionAttempts=a,this):this._reconnectionAttempts};a.prototype.reconnectionDelay=function(a){return arguments.length?(this._reconnectionDelay=a,this.backoff&&this.backoff.setMin(a),this):this._reconnectionDelay};a.prototype.randomizationFactor=function(a){return arguments.length?(this._randomizationFactor=a,this.backoff&&this.backoff.setJitter(a),this):this._randomizationFactor};a.prototype.reconnectionDelayMax=function(a){return arguments.length?(this._reconnectionDelayMax=
a,this.backoff&&this.backoff.setMax(a),this):this._reconnectionDelayMax};a.prototype.timeout=function(a){return arguments.length?(this._timeout=a,this):this._timeout};a.prototype.maybeReconnectOnOpen=function(){!this.reconnecting&&this._reconnection&&0===this.backoff.attempts&&this.reconnect()};a.prototype.open=a.prototype.connect=function(a,e){if(~this.readyState.indexOf("open"))return this;var c=this.engine=h(this.uri,this.opts),g=this;this.readyState="opening";this.skipReconnect=!1;var b=l(c,"open",
function(){g.onopen();a&&a()}),d=l(c,"error",function(e){if(g.cleanup(),g.readyState="closed",g.emitAll("connect_error",e),a){var c=Error("Connection error");c.data=e;a(c)}else g.maybeReconnectOnOpen()});if(!1!==this._timeout){var f=this._timeout,q=setTimeout(function(){b.destroy();c.close();c.emit("error","timeout");g.emitAll("connect_timeout",f)},f);this.subs.push({destroy:function(){clearTimeout(q)}})}return this.subs.push(b),this.subs.push(d),this};a.prototype.onopen=function(){this.cleanup();
this.readyState="open";this.emit("open");var a=this.engine;this.subs.push(l(a,"data",p(this,"ondata")));this.subs.push(l(a,"ping",p(this,"onping")));this.subs.push(l(a,"pong",p(this,"onpong")));this.subs.push(l(a,"error",p(this,"onerror")));this.subs.push(l(a,"close",p(this,"onclose")));this.subs.push(l(this.decoder,"decoded",p(this,"ondecoded")))};a.prototype.onping=function(){this.lastPing=new Date;this.emitAll("ping")};a.prototype.onpong=function(){this.emitAll("pong",new Date-this.lastPing)};
a.prototype.ondata=function(a){this.decoder.add(a)};a.prototype.ondecoded=function(a){this.emit("packet",a)};a.prototype.onerror=function(a){this.emitAll("error",a)};a.prototype.socket=function(a,e){function c(){~m(g.connecting,b)||g.connecting.push(b)}var b=this.nsps[a];if(!b){b=new k(this,a,e);this.nsps[a]=b;var g=this;b.on("connecting",c);b.on("connect",function(){b.id=g.generateId(a)});this.autoConnect&&c()}return b};a.prototype.destroy=function(a){a=m(this.connecting,a);~a&&this.connecting.splice(a,
1);this.connecting.length||this.close()};a.prototype.packet=function(a){var e=this;a.query&&0===a.type&&(a.nsp+="?"+a.query);e.encoding?e.packetBuffer.push(a):(e.encoding=!0,this.encoder.encode(a,function(c){for(var b=0;b<c.length;b++)e.engine.write(c[b],a.options);e.encoding=!1;e.processPacketQueue()}))};a.prototype.processPacketQueue=function(){if(0<this.packetBuffer.length&&!this.encoding){var a=this.packetBuffer.shift();this.packet(a)}};a.prototype.cleanup=function(){for(var a=this.subs.length,
e=0;e<a;e++)this.subs.shift().destroy();this.packetBuffer=[];this.encoding=!1;this.lastPing=null;this.decoder.destroy()};a.prototype.close=a.prototype.disconnect=function(){this.skipReconnect=!0;this.reconnecting=!1;"opening"===this.readyState&&this.cleanup();this.backoff.reset();this.readyState="closed";this.engine&&this.engine.close()};a.prototype.onclose=function(a){this.cleanup();this.backoff.reset();this.readyState="closed";this.emit("close",a);this._reconnection&&!this.skipReconnect&&this.reconnect()};
a.prototype.reconnect=function(){if(this.reconnecting||this.skipReconnect)return this;var a=this;if(this.backoff.attempts>=this._reconnectionAttempts)this.backoff.reset(),this.emitAll("reconnect_failed"),this.reconnecting=!1;else{var e=this.backoff.duration();this.reconnecting=!0;var c=setTimeout(function(){a.skipReconnect||(a.emitAll("reconnect_attempt",a.backoff.attempts),a.emitAll("reconnecting",a.backoff.attempts),a.skipReconnect||a.open(function(e){e?(a.reconnecting=!1,a.reconnect(),a.emitAll("reconnect_error",
e.data)):a.onreconnect()}))},e);this.subs.push({destroy:function(){clearTimeout(c)}})}};a.prototype.onreconnect=function(){var a=this.backoff.attempts;this.reconnecting=!1;this.backoff.reset();this.updateSocketIds();this.emitAll("reconnect",a)}},function(d,b,c){d.exports=c(11);d.exports.parser=c(18)},function(d,b,c){(function(a){function b(c,e){if(!(this instanceof b))return new b(c,e);e=e||{};c&&"object"==typeof c&&(e=c,c=null);c?(c=p(c),e.hostname=c.host,e.secure="https"===c.protocol||"wss"===c.protocol,
e.port=c.port,c.query&&(e.query=c.query)):e.host&&(e.hostname=p(e.host).host);this.secure=null!=e.secure?e.secure:a.location&&"https:"===location.protocol;e.hostname&&!e.port&&(e.port=this.secure?"443":"80");this.agent=e.agent||!1;this.hostname=e.hostname||(a.location?location.hostname:"localhost");this.port=e.port||(a.location&&location.port?location.port:this.secure?443:80);this.query=e.query||{};"string"==typeof this.query&&(this.query=m.decode(this.query));this.upgrade=!1!==e.upgrade;this.path=
(e.path||"/engine.io").replace(/\/$/,"")+"/";this.forceJSONP=!!e.forceJSONP;this.jsonp=!1!==e.jsonp;this.forceBase64=!!e.forceBase64;this.enablesXDR=!!e.enablesXDR;this.timestampParam=e.timestampParam||"t";this.timestampRequests=e.timestampRequests;this.transports=e.transports||["polling","websocket"];this.transportOptions=e.transportOptions||{};this.readyState="";this.writeBuffer=[];this.prevBufferLen=0;this.policyPort=e.policyPort||843;this.rememberUpgrade=e.rememberUpgrade||!1;this.binaryType=
null;this.onlyBinaryUpgrades=e.onlyBinaryUpgrades;this.perMessageDeflate=!1!==e.perMessageDeflate&&(e.perMessageDeflate||{});!0===this.perMessageDeflate&&(this.perMessageDeflate={});this.perMessageDeflate&&null==this.perMessageDeflate.threshold&&(this.perMessageDeflate.threshold=1024);this.pfx=e.pfx||null;this.key=e.key||null;this.passphrase=e.passphrase||null;this.cert=e.cert||null;this.ca=e.ca||null;this.ciphers=e.ciphers||null;this.rejectUnauthorized=void 0===e.rejectUnauthorized||e.rejectUnauthorized;
this.forceNode=!!e.forceNode;var d="object"==typeof a&&a;d.global===d&&(e.extraHeaders&&0<Object.keys(e.extraHeaders).length&&(this.extraHeaders=e.extraHeaders),e.localAddress&&(this.localAddress=e.localAddress));this.pingTimeoutTimer=this.pingIntervalTimer=this.pingTimeout=this.pingInterval=this.upgrades=this.id=null;this.open()}var h=c(12),k=c(5),n=(c(3)("engine.io-client:socket"),c(33)),l=c(18),p=c(2),m=c(27);d.exports=b;b.priorWebsocketSuccess=!1;k(b.prototype);b.protocol=l.protocol;b.Socket=
b;b.Transport=c(17);b.transports=c(12);b.parser=c(18);b.prototype.createTransport=function(a){var e=this.query,b={},c;for(c in e)e.hasOwnProperty(c)&&(b[c]=e[c]);b.EIO=l.protocol;b.transport=a;e=this.transportOptions[a]||{};this.id&&(b.sid=this.id);return new h[a]({query:b,socket:this,agent:e.agent||this.agent,hostname:e.hostname||this.hostname,port:e.port||this.port,secure:e.secure||this.secure,path:e.path||this.path,forceJSONP:e.forceJSONP||this.forceJSONP,jsonp:e.jsonp||this.jsonp,forceBase64:e.forceBase64||
this.forceBase64,enablesXDR:e.enablesXDR||this.enablesXDR,timestampRequests:e.timestampRequests||this.timestampRequests,timestampParam:e.timestampParam||this.timestampParam,policyPort:e.policyPort||this.policyPort,pfx:e.pfx||this.pfx,key:e.key||this.key,passphrase:e.passphrase||this.passphrase,cert:e.cert||this.cert,ca:e.ca||this.ca,ciphers:e.ciphers||this.ciphers,rejectUnauthorized:e.rejectUnauthorized||this.rejectUnauthorized,perMessageDeflate:e.perMessageDeflate||this.perMessageDeflate,extraHeaders:e.extraHeaders||
this.extraHeaders,forceNode:e.forceNode||this.forceNode,localAddress:e.localAddress||this.localAddress,requestTimeout:e.requestTimeout||this.requestTimeout,protocols:e.protocols||void 0})};b.prototype.open=function(){if(this.rememberUpgrade&&b.priorWebsocketSuccess&&-1!==this.transports.indexOf("websocket"))var a="websocket";else{if(0===this.transports.length){var e=this;return void setTimeout(function(){e.emit("error","No transports available")},0)}a=this.transports[0]}this.readyState="opening";
try{a=this.createTransport(a)}catch(g){return this.transports.shift(),void this.open()}a.open();this.setTransport(a)};b.prototype.setTransport=function(a){var e=this;this.transport&&this.transport.removeAllListeners();this.transport=a;a.on("drain",function(){e.onDrain()}).on("packet",function(a){e.onPacket(a)}).on("error",function(a){e.onError(a)}).on("close",function(){e.onClose("transport close")})};b.prototype.probe=function(a){function e(){if(m.onlyBinaryUpgrades){var a=!this.supportsBinary&&
m.transport.supportsBinary;p=p||a}p||(r.send([{type:"ping",data:"probe"}]),r.once("packet",function(a){if(!p)if("pong"===a.type&&"probe"===a.data){if(m.upgrading=!0,m.emit("upgrading",r),r)b.priorWebsocketSuccess="websocket"===r.name,m.transport.pause(function(){p||"closed"!==m.readyState&&(k(),m.setTransport(r),r.send([{type:"upgrade"}]),m.emit("upgrade",r),r=null,m.upgrading=!1,m.flush())})}else a=Error("probe error"),a.transport=r.name,m.emit("upgradeError",a)}))}function c(){p||(p=!0,k(),r.close(),
r=null)}function d(a){a=Error("probe error: "+a);a.transport=r.name;c();m.emit("upgradeError",a)}function f(){d("transport closed")}function h(){d("socket closed")}function q(a){r&&a.name!==r.name&&c()}function k(){r.removeListener("open",e);r.removeListener("error",d);r.removeListener("close",f);m.removeListener("close",h);m.removeListener("upgrading",q)}var r=this.createTransport(a,{probe:1}),p=!1,m=this;b.priorWebsocketSuccess=!1;r.once("open",e);r.once("error",d);r.once("close",f);this.once("close",
h);this.once("upgrading",q);r.open()};b.prototype.onOpen=function(){if(this.readyState="open",b.priorWebsocketSuccess="websocket"===this.transport.name,this.emit("open"),this.flush(),"open"===this.readyState&&this.upgrade&&this.transport.pause)for(var a=0,e=this.upgrades.length;a<e;a++)this.probe(this.upgrades[a])};b.prototype.onPacket=function(a){if("opening"===this.readyState||"open"===this.readyState||"closing"===this.readyState)switch(this.emit("packet",a),this.emit("heartbeat"),a.type){case "open":this.onHandshake(JSON.parse(a.data));
break;case "pong":this.setPing();this.emit("pong");break;case "error":var e=Error("server error");e.code=a.data;this.onError(e);break;case "message":this.emit("data",a.data),this.emit("message",a.data)}};b.prototype.onHandshake=function(a){this.emit("handshake",a);this.id=a.sid;this.transport.query.sid=a.sid;this.upgrades=this.filterUpgrades(a.upgrades);this.pingInterval=a.pingInterval;this.pingTimeout=a.pingTimeout;this.onOpen();"closed"!==this.readyState&&(this.setPing(),this.removeListener("heartbeat",
this.onHeartbeat),this.on("heartbeat",this.onHeartbeat))};b.prototype.onHeartbeat=function(a){clearTimeout(this.pingTimeoutTimer);var e=this;e.pingTimeoutTimer=setTimeout(function(){"closed"!==e.readyState&&e.onClose("ping timeout")},a||e.pingInterval+e.pingTimeout)};b.prototype.setPing=function(){var a=this;clearTimeout(a.pingIntervalTimer);a.pingIntervalTimer=setTimeout(function(){a.ping();a.onHeartbeat(a.pingTimeout)},a.pingInterval)};b.prototype.ping=function(){var a=this;this.sendPacket("ping",
function(){a.emit("ping")})};b.prototype.onDrain=function(){this.writeBuffer.splice(0,this.prevBufferLen);this.prevBufferLen=0;0===this.writeBuffer.length?this.emit("drain"):this.flush()};b.prototype.flush=function(){"closed"!==this.readyState&&this.transport.writable&&!this.upgrading&&this.writeBuffer.length&&(this.transport.send(this.writeBuffer),this.prevBufferLen=this.writeBuffer.length,this.emit("flush"))};b.prototype.write=b.prototype.send=function(a,e,b){return this.sendPacket("message",a,
e,b),this};b.prototype.sendPacket=function(a,e,b,c){if("function"==typeof e&&(c=e,e=void 0),"function"==typeof b&&(c=b,b=null),"closing"!==this.readyState&&"closed"!==this.readyState)b=b||{},b.compress=!1!==b.compress,a={type:a,data:e,options:b},this.emit("packetCreate",a),this.writeBuffer.push(a),c&&this.once("flush",c),this.flush()};b.prototype.close=function(){function a(){d.onClose("forced close");d.transport.close()}function b(){d.removeListener("upgrade",b);d.removeListener("upgradeError",b);
a()}function c(){d.once("upgrade",b);d.once("upgradeError",b)}if("opening"===this.readyState||"open"===this.readyState){this.readyState="closing";var d=this;this.writeBuffer.length?this.once("drain",function(){this.upgrading?c():a()}):this.upgrading?c():a()}return this};b.prototype.onError=function(a){b.priorWebsocketSuccess=!1;this.emit("error",a);this.onClose("transport error",a)};b.prototype.onClose=function(a,b){if("opening"===this.readyState||"open"===this.readyState||"closing"===this.readyState)clearTimeout(this.pingIntervalTimer),
clearTimeout(this.pingTimeoutTimer),this.transport.removeAllListeners("close"),this.transport.close(),this.transport.removeAllListeners(),this.readyState="closed",this.id=null,this.emit("close",a,b),this.writeBuffer=[],this.prevBufferLen=0};b.prototype.filterUpgrades=function(a){for(var b=[],c=0,d=a.length;c<d;c++)~n(this.transports,a[c])&&b.push(a[c]);return b}}).call(b,function(){return this}())},function(d,b,c){(function(a){var d=c(13),h=c(15),k=c(30),n=c(31);b.polling=function(b){var c,f=!1,n=
!1,e=!1!==b.jsonp;a.location&&(n="https:"===location.protocol,(f=location.port)||(f=n?443:80),f=b.hostname!==location.hostname||f!==b.port,n=b.secure!==n);if(b.xdomain=f,b.xscheme=n,c=new d(b),"open"in c&&!b.forceJSONP)return new h(b);if(!e)throw Error("JSONP disabled");return new k(b)};b.websocket=n}).call(b,function(){return this}())},function(d,b,c){(function(a){var b=c(14);d.exports=function(c){var d=c.xdomain,f=c.xscheme;c=c.enablesXDR;try{if("undefined"!=typeof XMLHttpRequest&&(!d||b))return new XMLHttpRequest}catch(l){}try{if("undefined"!=
typeof XDomainRequest&&!f&&c)return new XDomainRequest}catch(l){}if(!d)try{return new (a[["Active"].concat("Object").join("X")])("Microsoft.XMLHTTP")}catch(l){}}}).call(b,function(){return this}())},function(d,b){try{d.exports="undefined"!=typeof XMLHttpRequest&&"withCredentials"in new XMLHttpRequest}catch(c){d.exports=!1}},function(d,b,c){(function(a){function b(){}function h(b){if(p.call(this,b),this.requestTimeout=b.requestTimeout,this.extraHeaders=b.extraHeaders,a.location){var c="https:"===location.protocol,
e=location.port;e||(e=c?443:80);this.xd=b.hostname!==a.location.hostname||e!==b.port;this.xs=b.secure!==c}}function k(a){this.method=a.method||"GET";this.uri=a.uri;this.xd=!!a.xd;this.xs=!!a.xs;this.async=!1!==a.async;this.data=void 0!==a.data?a.data:null;this.agent=a.agent;this.isBinary=a.isBinary;this.supportsBinary=a.supportsBinary;this.enablesXDR=a.enablesXDR;this.requestTimeout=a.requestTimeout;this.pfx=a.pfx;this.key=a.key;this.passphrase=a.passphrase;this.cert=a.cert;this.ca=a.ca;this.ciphers=
a.ciphers;this.rejectUnauthorized=a.rejectUnauthorized;this.extraHeaders=a.extraHeaders;this.create()}function n(){for(var a in k.requests)k.requests.hasOwnProperty(a)&&k.requests[a].abort()}var l=c(13),p=c(16),m=c(5),q=c(28);c(3)("engine.io-client:polling-xhr");d.exports=h;d.exports.Request=k;q(h,p);h.prototype.supportsBinary=!0;h.prototype.request=function(a){return a=a||{},a.uri=this.uri(),a.xd=this.xd,a.xs=this.xs,a.agent=this.agent||!1,a.supportsBinary=this.supportsBinary,a.enablesXDR=this.enablesXDR,
a.pfx=this.pfx,a.key=this.key,a.passphrase=this.passphrase,a.cert=this.cert,a.ca=this.ca,a.ciphers=this.ciphers,a.rejectUnauthorized=this.rejectUnauthorized,a.requestTimeout=this.requestTimeout,a.extraHeaders=this.extraHeaders,new k(a)};h.prototype.doWrite=function(a,b){var c=this.request({method:"POST",data:a,isBinary:"string"!=typeof a&&void 0!==a}),e=this;c.on("success",b);c.on("error",function(a){e.onError("xhr post error",a)});this.sendXhr=c};h.prototype.doPoll=function(){var a=this.request(),
b=this;a.on("data",function(a){b.onData(a)});a.on("error",function(a){b.onError("xhr poll error",a)});this.pollXhr=a};m(k.prototype);k.prototype.create=function(){var b={agent:this.agent,xdomain:this.xd,xscheme:this.xs,enablesXDR:this.enablesXDR};b.pfx=this.pfx;b.key=this.key;b.passphrase=this.passphrase;b.cert=this.cert;b.ca=this.ca;b.ciphers=this.ciphers;b.rejectUnauthorized=this.rejectUnauthorized;var c=this.xhr=new l(b),d=this;try{c.open(this.method,this.uri,this.async);try{if(this.extraHeaders){c.setDisableHeaderCheck&&
c.setDisableHeaderCheck(!0);for(var f in this.extraHeaders)this.extraHeaders.hasOwnProperty(f)&&c.setRequestHeader(f,this.extraHeaders[f])}}catch(u){}if("POST"===this.method)try{this.isBinary?c.setRequestHeader("Content-type","application/octet-stream"):c.setRequestHeader("Content-type","text/plain;charset=UTF-8")}catch(u){}try{c.setRequestHeader("Accept","*/*")}catch(u){}"withCredentials"in c&&(c.withCredentials=!0);this.requestTimeout&&(c.timeout=this.requestTimeout);this.hasXDR()?(c.onload=function(){d.onLoad()},
c.onerror=function(){d.onError(c.responseText)}):c.onreadystatechange=function(){if(2===c.readyState)try{var a=c.getResponseHeader("Content-Type");d.supportsBinary&&"application/octet-stream"===a&&(c.responseType="arraybuffer")}catch(v){}4===c.readyState&&(200===c.status||1223===c.status?d.onLoad():setTimeout(function(){d.onError(c.status)},0))};c.send(this.data)}catch(u){return void setTimeout(function(){d.onError(u)},0)}a.document&&(this.index=k.requestsCount++,k.requests[this.index]=this)};k.prototype.onSuccess=
function(){this.emit("success");this.cleanup()};k.prototype.onData=function(a){this.emit("data",a);this.onSuccess()};k.prototype.onError=function(a){this.emit("error",a);this.cleanup(!0)};k.prototype.cleanup=function(c){if("undefined"!=typeof this.xhr&&null!==this.xhr){if(this.hasXDR()?this.xhr.onload=this.xhr.onerror=b:this.xhr.onreadystatechange=b,c)try{this.xhr.abort()}catch(g){}a.document&&delete k.requests[this.index];this.xhr=null}};k.prototype.onLoad=function(){try{try{var a=this.xhr.getResponseHeader("Content-Type")}catch(t){}var b=
"application/octet-stream"===a?this.xhr.response||this.xhr.responseText:this.xhr.responseText}catch(t){this.onError(t)}null!=b&&this.onData(b)};k.prototype.hasXDR=function(){return"undefined"!=typeof a.XDomainRequest&&!this.xs&&this.enablesXDR};k.prototype.abort=function(){this.cleanup()};k.requestsCount=0;k.requests={};a.document&&(a.attachEvent?a.attachEvent("onunload",n):a.addEventListener&&a.addEventListener("beforeunload",n,!1))}).call(b,function(){return this}())},function(d,b,c){function a(a){var b=
a&&a.forceBase64;l&&!b||(this.supportsBinary=!1);f.call(this,a)}var f=c(17),h=c(27),k=c(18);b=c(28);var n=c(29);c(3)("engine.io-client:polling");d.exports=a;var l=null!=(new (c(13))({xdomain:!1})).responseType;b(a,f);a.prototype.name="polling";a.prototype.doOpen=function(){this.poll()};a.prototype.pause=function(a){function b(){c.readyState="paused";a()}var c=this;if(this.readyState="pausing",this.polling||!this.writable){var d=0;this.polling&&(d++,this.once("pollComplete",function(){--d||b()}));
this.writable||(d++,this.once("drain",function(){--d||b()}))}else b()};a.prototype.poll=function(){this.polling=!0;this.doPoll();this.emit("poll")};a.prototype.onData=function(a){var b=this;k.decodePayload(a,this.socket.binaryType,function(a,c,d){return"opening"===b.readyState&&b.onOpen(),"close"===a.type?(b.onClose(),!1):void b.onPacket(a)});"closed"!==this.readyState&&(this.polling=!1,this.emit("pollComplete"),"open"===this.readyState&&this.poll())};a.prototype.doClose=function(){function a(){b.write([{type:"close"}])}
var b=this;"open"===this.readyState?a():this.once("open",a)};a.prototype.write=function(a){var b=this;this.writable=!1;var c=function(){b.writable=!0;b.emit("drain")};k.encodePayload(a,this.supportsBinary,function(a){b.doWrite(a,c)})};a.prototype.uri=function(){var a=this.query||{},b=this.secure?"https":"http",c="";!1!==this.timestampRequests&&(a[this.timestampParam]=n());this.supportsBinary||a.sid||(a.b64=1);a=h.encode(a);this.port&&("https"===b&&443!==Number(this.port)||"http"===b&&80!==Number(this.port))&&
(c=":"+this.port);a.length&&(a="?"+a);var d=-1!==this.hostname.indexOf(":");return b+"://"+(d?"["+this.hostname+"]":this.hostname)+c+this.path+a}},function(d,b,c){function a(a){this.path=a.path;this.hostname=a.hostname;this.port=a.port;this.secure=a.secure;this.query=a.query;this.timestampParam=a.timestampParam;this.timestampRequests=a.timestampRequests;this.readyState="";this.agent=a.agent||!1;this.socket=a.socket;this.enablesXDR=a.enablesXDR;this.pfx=a.pfx;this.key=a.key;this.passphrase=a.passphrase;
this.cert=a.cert;this.ca=a.ca;this.ciphers=a.ciphers;this.rejectUnauthorized=a.rejectUnauthorized;this.forceNode=a.forceNode;this.extraHeaders=a.extraHeaders;this.localAddress=a.localAddress}var f=c(18);b=c(5);d.exports=a;b(a.prototype);a.prototype.onError=function(a,b){var c=Error(a);return c.type="TransportError",c.description=b,this.emit("error",c),this};a.prototype.open=function(){return"closed"!==this.readyState&&""!==this.readyState||(this.readyState="opening",this.doOpen()),this};a.prototype.close=
function(){return"opening"!==this.readyState&&"open"!==this.readyState||(this.doClose(),this.onClose()),this};a.prototype.send=function(a){if("open"!==this.readyState)throw Error("Transport not open");this.write(a)};a.prototype.onOpen=function(){this.readyState="open";this.writable=!0;this.emit("open")};a.prototype.onData=function(a){a=f.decodePacket(a,this.socket.binaryType);this.onPacket(a)};a.prototype.onPacket=function(a){this.emit("packet",a)};a.prototype.onClose=function(){this.readyState="closed";
this.emit("close")}},function(d,b,c){(function(a){function d(a,c,d){if(!c)return b.encodeBase64Packet(a,d);var e=new FileReader;return e.onload=function(){a.data=e.result;b.encodePacket(a,c,!0,d)},e.readAsArrayBuffer(a.data)}function h(a,b,c){var d=Array(a.length);c=m(a.length,c);for(var e=function(a,c,e){b(c,function(b,c){d[a]=c;e(b,d)})},g=0;g<a.length;g++)e(g,a[g],c)}var k,n=c(19),l=c(20),p=c(21),m=c(22),q=c(23);a&&a.ArrayBuffer&&(k=c(25));var e="undefined"!=typeof navigator&&/Android/i.test(navigator.userAgent),
g="undefined"!=typeof navigator&&/PhantomJS/i.test(navigator.userAgent),t=e||g;b.protocol=3;var x=b.packets={open:0,close:1,ping:2,pong:3,message:4,upgrade:5,noop:6},u=n(x),v={type:"error",data:"parser error"},w=c(26);b.encodePacket=function(c,e,g,f){"function"==typeof e&&(f=e,e=!1);"function"==typeof g&&(f=g,g=null);var h=void 0===c.data?void 0:c.data.buffer||c.data;if(a.ArrayBuffer&&h instanceof ArrayBuffer){if(e){g=c.data;e=new Uint8Array(g);g=new Uint8Array(1+g.byteLength);g[0]=x[c.type];for(c=
0;c<e.length;c++)g[c+1]=e[c];c=f(g.buffer)}else c=b.encodeBase64Packet(c,f);return c}if(w&&h instanceof a.Blob)return e?t?c=d(c,e,f):(e=new Uint8Array(1),e[0]=x[c.type],c=new w([e.buffer,c.data]),c=f(c)):c=b.encodeBase64Packet(c,f),c;if(h&&h.base64)return f("b"+b.packets[c.type]+c.data.data);e=x[c.type];return void 0!==c.data&&(e+=g?q.encode(String(c.data),{strict:!1}):String(c.data)),f(""+e)};b.encodeBase64Packet=function(c,d){var e="b"+b.packets[c.type];if(w&&c.data instanceof a.Blob){var g=new FileReader;
return g.onload=function(){var a=g.result.split(",")[1];d(e+a)},g.readAsDataURL(c.data)}try{var f=String.fromCharCode.apply(null,new Uint8Array(c.data))}catch(A){f=new Uint8Array(c.data);for(var h=Array(f.length),k=0;k<f.length;k++)h[k]=f[k];f=String.fromCharCode.apply(null,h)}return e+=a.btoa(f),d(e)};b.decodePacket=function(a,c,d){if(void 0===a)return v;if("string"==typeof a){if("b"===a.charAt(0))return b.decodeBase64Packet(a.substr(1),c);if(c=d){c=a;try{c=q.decode(c,{strict:!1})}catch(z){c=!1}c=
(a=c,!1===a)}if(c)return v;d=a.charAt(0);return Number(d)==d&&u[d]?1<a.length?{type:u[d],data:a.substring(1)}:{type:u[d]}:v}d=(new Uint8Array(a))[0];a=p(a,1);return w&&"blob"===c&&(a=new w([a])),{type:u[d],data:a}};b.decodeBase64Packet=function(a,c){var b=u[a.charAt(0)];if(!k)return{type:b,data:{base64:!0,data:a.substr(1)}};var d=k.decode(a.substr(1));return"blob"===c&&w&&(d=new w([d])),{type:b,data:d}};b.encodePayload=function(a,c,d){function e(a,d){b.encodePacket(a,!!g&&c,!1,function(a){d(null,
a.length+":"+a)})}"function"==typeof c&&(d=c,c=null);var g=l(a);return c&&g?w&&!t?b.encodePayloadAsBlob(a,d):b.encodePayloadAsArrayBuffer(a,d):a.length?void h(a,e,function(a,c){return d(c.join(""))}):d("0:")};b.decodePayload=function(a,c,d){if("string"!=typeof a)return b.decodePayloadAsBinary(a,c,d);"function"==typeof c&&(d=c,c=null);var e;if(""===a)return d(v,0,1);for(var g,f,h="",k=0,m=a.length;k<m;k++){var p=a.charAt(k);if(":"===p){if(""===h||h!=(g=Number(h))||(f=a.substr(k+1,g),h!=f.length))return d(v,
0,1);if(f.length){if(e=b.decodePacket(f,c,!1),v.type===e.type&&v.data===e.data)return d(v,0,1);if(!1===d(e,k+g,m))return}k+=g;h=""}else h+=p}return""!==h?d(v,0,1):void 0};b.encodePayloadAsArrayBuffer=function(a,c){function d(a,c){b.encodePacket(a,!0,!0,function(a){return c(null,a)})}return a.length?void h(a,d,function(a,b){var d=b.reduce(function(a,c){var b;return b="string"==typeof c?c.length:c.byteLength,a+b.toString().length+b+2},0),e=new Uint8Array(d),g=0;return b.forEach(function(a){var c="string"==
typeof a,b=a;if(c){b=new Uint8Array(a.length);for(var d=0;d<a.length;d++)b[d]=a.charCodeAt(d);b=b.buffer}c?e[g++]=0:e[g++]=1;a=b.byteLength.toString();for(d=0;d<a.length;d++)e[g++]=parseInt(a[d]);e[g++]=255;b=new Uint8Array(b);for(d=0;d<b.length;d++)e[g++]=b[d]}),c(e.buffer)}):c(new ArrayBuffer(0))};b.encodePayloadAsBlob=function(a,c){h(a,function(a,c){b.encodePacket(a,!0,!0,function(a){var b=new Uint8Array(1);if(b[0]=1,"string"==typeof a){for(var d=new Uint8Array(a.length),e=0;e<a.length;e++)d[e]=
a.charCodeAt(e);a=d.buffer;b[0]=0}d=(a instanceof ArrayBuffer?a.byteLength:a.size).toString();var g=new Uint8Array(d.length+1);for(e=0;e<d.length;e++)g[e]=parseInt(d[e]);if(g[d.length]=255,w)a=new w([b.buffer,g.buffer,a]),c(null,a)})},function(a,b){return c(new w(b))})};b.decodePayloadAsBinary=function(a,c,d){"function"==typeof c&&(d=c,c=null);for(var e=[];0<a.byteLength;){for(var g=new Uint8Array(a),f=0===g[0],h="",k=1;255!==g[k];k++){if(310<h.length)return d(v,0,1);h+=g[k]}a=p(a,2+h.length);h=parseInt(h);
g=p(a,0,h);if(f)try{g=String.fromCharCode.apply(null,new Uint8Array(g))}catch(B){for(f=new Uint8Array(g),g="",k=0;k<f.length;k++)g+=String.fromCharCode(f[k])}e.push(g);a=p(a,h)}var m=e.length;e.forEach(function(a,e){d(b.decodePacket(a,c,!0),e,m)})}}).call(b,function(){return this}())},function(d,b){d.exports=Object.keys||function(c){var a=[],b=Object.prototype.hasOwnProperty,d;for(d in c)b.call(c,d)&&a.push(d);return a}},function(d,b,c){(function(a){function b(c){if(!c||"object"!=typeof c)return!1;
if(h(c)){for(var d=0,f=c.length;d<f;d++)if(b(c[d]))return!0;return!1}if("function"==typeof a.Buffer&&a.Buffer.isBuffer&&a.Buffer.isBuffer(c)||"function"==typeof a.ArrayBuffer&&c instanceof ArrayBuffer||n&&c instanceof Blob||l&&c instanceof File)return!0;if(c.toJSON&&"function"==typeof c.toJSON&&1===arguments.length)return b(c.toJSON(),!0);for(d in c)if(Object.prototype.hasOwnProperty.call(c,d)&&b(c[d]))return!0;return!1}var h=c(7),k=Object.prototype.toString,n="function"==typeof a.Blob||"[object BlobConstructor]"===
k.call(a.Blob),l="function"==typeof a.File||"[object FileConstructor]"===k.call(a.File);d.exports=b}).call(b,function(){return this}())},function(d,b){d.exports=function(c,a,b){var d=c.byteLength;if(a=a||0,b=b||d,c.slice)return c.slice(a,b);if(0>a&&(a+=d),0>b&&(b+=d),b>d&&(b=d),a>=d||a>=b||0===d)return new ArrayBuffer(0);c=new Uint8Array(c);d=new Uint8Array(b-a);for(var f=0;a<b;a++,f++)d[f]=c[a];return d.buffer}},function(d,b){function c(){}d.exports=function(a,b,d){function f(a,c){if(0>=f.count)throw Error("after called too many times");
--f.count;a?(h=!0,b(a),b=d):0!==f.count||h||b(null,c)}var h=!1;return d=d||c,f.count=a,0===a?b():f}},function(d,b,c){var a;(function(c,d){!function(d){function f(a){for(var c,b,d=[],e=0,g=a.length;e<g;)c=a.charCodeAt(e++),55296<=c&&56319>=c&&e<g?(b=a.charCodeAt(e++),56320==(64512&b)?d.push(((1023&c)<<10)+(1023&b)+65536):(d.push(c),e--)):d.push(c);return d}function h(a,c){if(55296<=a&&57343>=a){if(c)throw Error("Lone surrogate U+"+a.toString(16).toUpperCase()+" is not a scalar value");return!1}return!0}
function k(){if(g>=e)throw Error("Invalid byte index");var a=255&q[g];if(g++,128==(192&a))return 63&a;throw Error("Invalid continuation byte");}function m(a){var c,b,d,f,m;if(g>e)throw Error("Invalid byte index");if(g==e)return!1;if(c=255&q[g],g++,0==(128&c))return c;if(192==(224&c)){if(b=k(),m=(31&c)<<6|b,128<=m)return m;throw Error("Invalid continuation byte");}if(224==(240&c)){if(b=k(),d=k(),m=(15&c)<<12|b<<6|d,2048<=m)return h(m,a)?m:65533;throw Error("Invalid continuation byte");}if(240==(248&
c)&&(b=k(),d=k(),f=k(),m=(7&c)<<18|b<<12|d<<6|f,65536<=m&&1114111>=m))return m;throw Error("Invalid UTF-8 detected");}d="object"==typeof b&&b;"object"==typeof c&&c&&c.exports==d&&c;var q,e,g,t=String.fromCharCode;a={version:"2.1.2",encode:function(a,c){c=c||{};for(var b,d=!1!==c.strict,e=f(a),g=e.length,k=-1,m="";++k<g;){b=e[k];var n=d;if(0==(4294967168&b))n=t(b);else{var l="";n=(0==(4294965248&b)?l=t(b>>6&31|192):0==(4294901760&b)?(h(b,n)||(b=65533),l=t(b>>12&15|224),l+=t(b>>6&63|128)):0==(4292870144&
b)&&(l=t(b>>18&7|240),l+=t(b>>12&63|128),l+=t(b>>6&63|128)),l+t(63&b|128))}m+=n}return m},decode:function(a,c){c=c||{};var b=!1!==c.strict;q=f(a);e=q.length;g=0;for(var d,h=[];!1!==(d=m(b));)h.push(d);d=h.length;for(var k=-1,l="";++k<d;)b=h[k],65535<b&&(b-=65536,l+=t(b>>>10&1023|55296),b=56320|1023&b),l+=t(b);return l}};!(void 0!==a&&(c.exports=a))}(this)}).call(b,c(24)(d),function(){return this}())},function(d,b){d.exports=function(c){return c.webpackPolyfill||(c.deprecate=function(){},c.paths=[],
c.children=[],c.webpackPolyfill=1),c}},function(d,b){!function(){for(var c=new Uint8Array(256),a=0;64>a;a++)c["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(a)]=a;b.encode=function(a){var c=new Uint8Array(a),b=c.length,d="";for(a=0;a<b;a+=3)d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[c[a]>>2],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(3&c[a])<<4|c[a+1]>>4],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(15&
c[a+1])<<2|c[a+2]>>6],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[63&c[a+2]];return 2===b%3?d=d.substring(0,d.length-1)+"=":1===b%3&&(d=d.substring(0,d.length-2)+"=="),d};b.decode=function(a){var b=.75*a.length;var d=a.length,f=0;"="===a[a.length-1]&&(b--,"="===a[a.length-2]&&b--);var l=new ArrayBuffer(b),p=new Uint8Array(l);for(b=0;b<d;b+=4){var m=c[a.charCodeAt(b)];var q=c[a.charCodeAt(b+1)];var e=c[a.charCodeAt(b+2)];var g=c[a.charCodeAt(b+3)];p[f++]=m<<2|q>>4;p[f++]=
(15&q)<<4|e>>2;p[f++]=(3&e)<<6|63&g}return l}}()},function(d,b){(function(c){function a(a){for(var c=0;c<a.length;c++){var b=a[c];if(b.buffer instanceof ArrayBuffer){var d=b.buffer;if(b.byteLength!==d.byteLength){var f=new Uint8Array(b.byteLength);f.set(new Uint8Array(d,b.byteOffset,b.byteLength));d=f.buffer}a[c]=d}}}function b(c,b){b=b||{};var d=new k;a(c);for(var g=0;g<c.length;g++)d.append(c[g]);return b.type?d.getBlob(b.type):d.getBlob()}function h(c,b){return a(c),new Blob(c,b||{})}var k=c.BlobBuilder||
c.WebKitBlobBuilder||c.MSBlobBuilder||c.MozBlobBuilder;try{var n=2===(new Blob(["hi"])).size}catch(m){n=!1}var l;if(l=n)try{l=2===(new Blob([new Uint8Array([1,2])])).size}catch(m){l=!1}var p=k&&k.prototype.append&&k.prototype.getBlob;d.exports=n?l?c.Blob:h:p?b:void 0}).call(b,function(){return this}())},function(d,b){b.encode=function(c){var a="",b;for(b in c)c.hasOwnProperty(b)&&(a.length&&(a+="&"),a+=encodeURIComponent(b)+"="+encodeURIComponent(c[b]));return a};b.decode=function(c){var a={};c=c.split("&");
for(var b=0,d=c.length;b<d;b++){var k=c[b].split("=");a[decodeURIComponent(k[0])]=decodeURIComponent(k[1])}return a}},function(d,b){d.exports=function(c,a){var b=function(){};b.prototype=a.prototype;c.prototype=new b;c.prototype.constructor=c}},function(d,b){function c(a){var c="";do c=h[a%k]+c,a=Math.floor(a/k);while(0<a);return c}function a(){var a=c(+new Date);return a!==f?(l=0,f=a):a+"."+c(l++)}for(var f,h="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_".split(""),k=64,n={},
l=0,p=0;p<k;p++)n[h[p]]=p;a.encode=c;a.decode=function(a){var c=0;for(p=0;p<a.length;p++)c=c*k+n[a.charAt(p)];return c};d.exports=a},function(d,b,c){(function(a){function b(){}function h(c){k.call(this,c);this.query=this.query||{};l||(a.___eio||(a.___eio=[]),l=a.___eio);this.index=l.length;var d=this;l.push(function(a){d.onData(a)});this.query.j=this.index;a.document&&a.addEventListener&&a.addEventListener("beforeunload",function(){d.script&&(d.script.onerror=b)},!1)}var k=c(16),n=c(28);d.exports=
h;var l,p=/\n/g,m=/\\n/g;n(h,k);h.prototype.supportsBinary=!1;h.prototype.doClose=function(){this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);this.form&&(this.form.parentNode.removeChild(this.form),this.form=null,this.iframe=null);k.prototype.doClose.call(this)};h.prototype.doPoll=function(){var a=this,c=document.createElement("script");this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);c.async=!0;c.src=this.uri();c.onerror=function(c){a.onError("jsonp poll error",
c)};var b=document.getElementsByTagName("script")[0];b?b.parentNode.insertBefore(c,b):(document.head||document.body).appendChild(c);this.script=c;"undefined"!=typeof navigator&&/gecko/i.test(navigator.userAgent)&&setTimeout(function(){var a=document.createElement("iframe");document.body.appendChild(a);document.body.removeChild(a)},100)};h.prototype.doWrite=function(a,c){function b(){d();c()}function d(){if(e.iframe)try{e.form.removeChild(e.iframe)}catch(y){e.onError("jsonp polling iframe removal error",
y)}try{f=document.createElement('<iframe src="javascript:0" name="'+e.iframeId+'">')}catch(y){f=document.createElement("iframe"),f.name=e.iframeId,f.src="javascript:0"}f.id=e.iframeId;e.form.appendChild(f);e.iframe=f}var e=this;if(!this.form){var f,h=document.createElement("form"),k=document.createElement("textarea"),l=this.iframeId="eio_iframe_"+this.index;h.className="socketio";h.style.position="absolute";h.style.top="-1000px";h.style.left="-1000px";h.target=l;h.method="POST";h.setAttribute("accept-charset",
"utf-8");k.name="d";h.appendChild(k);document.body.appendChild(h);this.form=h;this.area=k}this.form.action=this.uri();d();a=a.replace(m,"\\\n");this.area.value=a.replace(p,"\\n");try{this.form.submit()}catch(y){}this.iframe.attachEvent?this.iframe.onreadystatechange=function(){"complete"===e.iframe.readyState&&b()}:this.iframe.onload=b}}).call(b,function(){return this}())},function(d,b,c){(function(a){function b(a){a&&a.forceBase64&&(this.supportsBinary=!1);this.perMessageDeflate=a.perMessageDeflate;
this.usingBrowserWebSocket=m&&!a.forceNode;this.protocols=a.protocols;this.usingBrowserWebSocket||(e=q);h.call(this,a)}var h=c(17),k=c(18),n=c(27),l=c(28),p=c(29),m=(c(3)("engine.io-client:websocket"),a.WebSocket||a.MozWebSocket);if("undefined"==typeof window)try{var q=c(32)}catch(g){}var e=m;e||"undefined"!=typeof window||(e=q);d.exports=b;l(b,h);b.prototype.name="websocket";b.prototype.supportsBinary=!0;b.prototype.doOpen=function(){if(this.check()){var a=this.uri(),c=this.protocols,b={agent:this.agent,
perMessageDeflate:this.perMessageDeflate};b.pfx=this.pfx;b.key=this.key;b.passphrase=this.passphrase;b.cert=this.cert;b.ca=this.ca;b.ciphers=this.ciphers;b.rejectUnauthorized=this.rejectUnauthorized;this.extraHeaders&&(b.headers=this.extraHeaders);this.localAddress&&(b.localAddress=this.localAddress);try{this.ws=this.usingBrowserWebSocket?c?new e(a,c):new e(a):new e(a,c,b)}catch(u){return this.emit("error",u)}void 0===this.ws.binaryType&&(this.supportsBinary=!1);this.ws.supports&&this.ws.supports.binary?
(this.supportsBinary=!0,this.ws.binaryType="nodebuffer"):this.ws.binaryType="arraybuffer";this.addEventListeners()}};b.prototype.addEventListeners=function(){var a=this;this.ws.onopen=function(){a.onOpen()};this.ws.onclose=function(){a.onClose()};this.ws.onmessage=function(b){a.onData(b.data)};this.ws.onerror=function(b){a.onError("websocket error",b)}};b.prototype.write=function(b){function c(){d.emit("flush");setTimeout(function(){d.writable=!0;d.emit("drain")},0)}var d=this;this.writable=!1;for(var e=
b.length,g=0,f=e;g<f;g++)!function(b){k.encodePacket(b,d.supportsBinary,function(g){if(!d.usingBrowserWebSocket){var f={};(b.options&&(f.compress=b.options.compress),d.perMessageDeflate)&&("string"==typeof g?a.Buffer.byteLength(g):g.length)<d.perMessageDeflate.threshold&&(f.compress=!1)}try{d.usingBrowserWebSocket?d.ws.send(g):d.ws.send(g,f)}catch(z){}--e||c()})}(b[g])};b.prototype.onClose=function(){h.prototype.onClose.call(this)};b.prototype.doClose=function(){"undefined"!=typeof this.ws&&this.ws.close()};
b.prototype.uri=function(){var a=this.query||{},b=this.secure?"wss":"ws",c="";this.port&&("wss"===b&&443!==Number(this.port)||"ws"===b&&80!==Number(this.port))&&(c=":"+this.port);this.timestampRequests&&(a[this.timestampParam]=p());this.supportsBinary||(a.b64=1);a=n.encode(a);a.length&&(a="?"+a);var d=-1!==this.hostname.indexOf(":");return b+"://"+(d?"["+this.hostname+"]":this.hostname)+c+this.path+a};b.prototype.check=function(){return!(!e||"__initialize"in e&&this.name===b.prototype.name)}}).call(b,
function(){return this}())},function(d,b){},function(d,b){var c=[].indexOf;d.exports=function(a,b){if(c)return a.indexOf(b);for(var d=0;d<a.length;++d)if(a[d]===b)return d;return-1}},function(d,b,c){function a(a,b,c){this.io=a;this.nsp=b;this.json=this;this.ids=0;this.acks={};this.receiveBuffer=[];this.sendBuffer=[];this.connected=!1;this.disconnected=!0;this.flags={};c&&c.query&&(this.query=c.query);this.io.autoConnect&&this.open()}var f="function"==typeof Symbol&&"symbol"==typeof Symbol.iterator?
function(a){return typeof a}:function(a){return a&&"function"==typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},h=c(4);b=c(5);var k=c(35),n=c(36),l=c(37),p=(c(3)("socket.io-client:socket"),c(27)),m=c(20);d.exports=a;var q={connect:1,connect_error:1,connect_timeout:1,connecting:1,disconnect:1,error:1,reconnect:1,reconnect_attempt:1,reconnect_failed:1,reconnect_error:1,reconnecting:1,ping:1,pong:1},e=b.prototype.emit;b(a.prototype);a.prototype.subEvents=function(){if(!this.subs){var a=
this.io;this.subs=[n(a,"open",l(this,"onopen")),n(a,"packet",l(this,"onpacket")),n(a,"close",l(this,"onclose"))]}};a.prototype.open=a.prototype.connect=function(){return this.connected?this:(this.subEvents(),this.io.open(),"open"===this.io.readyState&&this.onopen(),this.emit("connecting"),this)};a.prototype.send=function(){var a=k(arguments);return a.unshift("message"),this.emit.apply(this,a),this};a.prototype.emit=function(a){if(q.hasOwnProperty(a))return e.apply(this,arguments),this;var b=k(arguments),
c={type:(void 0!==this.flags.binary?this.flags.binary:m(b))?h.BINARY_EVENT:h.EVENT,data:b};return c.options={},c.options.compress=!this.flags||!1!==this.flags.compress,"function"==typeof b[b.length-1]&&(this.acks[this.ids]=b.pop(),c.id=this.ids++),this.connected?this.packet(c):this.sendBuffer.push(c),this.flags={},this};a.prototype.packet=function(a){a.nsp=this.nsp;this.io.packet(a)};a.prototype.onopen=function(){if("/"!==this.nsp)if(this.query){var a="object"===f(this.query)?p.encode(this.query):
this.query;this.packet({type:h.CONNECT,query:a})}else this.packet({type:h.CONNECT})};a.prototype.onclose=function(a){this.connected=!1;this.disconnected=!0;delete this.id;this.emit("disconnect",a)};a.prototype.onpacket=function(a){var b=a.type===h.ERROR&&"/"===a.nsp;if(a.nsp===this.nsp||b)switch(a.type){case h.CONNECT:this.onconnect();break;case h.EVENT:this.onevent(a);break;case h.BINARY_EVENT:this.onevent(a);break;case h.ACK:this.onack(a);break;case h.BINARY_ACK:this.onack(a);break;case h.DISCONNECT:this.ondisconnect();
break;case h.ERROR:this.emit("error",a.data)}};a.prototype.onevent=function(a){var b=a.data||[];null!=a.id&&b.push(this.ack(a.id));this.connected?e.apply(this,b):this.receiveBuffer.push(b)};a.prototype.ack=function(a){var b=this,c=!1;return function(){if(!c){c=!0;var d=k(arguments);b.packet({type:m(d)?h.BINARY_ACK:h.ACK,id:a,data:d})}}};a.prototype.onack=function(a){var b=this.acks[a.id];"function"==typeof b&&(b.apply(this,a.data),delete this.acks[a.id])};a.prototype.onconnect=function(){this.connected=
!0;this.disconnected=!1;this.emit("connect");this.emitBuffered()};a.prototype.emitBuffered=function(){var a;for(a=0;a<this.receiveBuffer.length;a++)e.apply(this,this.receiveBuffer[a]);this.receiveBuffer=[];for(a=0;a<this.sendBuffer.length;a++)this.packet(this.sendBuffer[a]);this.sendBuffer=[]};a.prototype.ondisconnect=function(){this.destroy();this.onclose("io server disconnect")};a.prototype.destroy=function(){if(this.subs){for(var a=0;a<this.subs.length;a++)this.subs[a].destroy();this.subs=null}this.io.destroy(this)};
a.prototype.close=a.prototype.disconnect=function(){return this.connected&&this.packet({type:h.DISCONNECT}),this.destroy(),this.connected&&this.onclose("io client disconnect"),this};a.prototype.compress=function(a){return this.flags.compress=a,this};a.prototype.binary=function(a){return this.flags.binary=a,this}},function(d,b){d.exports=function(b,a){for(var c=[],d=(a=a||0)||0;d<b.length;d++)c[d-a]=b[d];return c}},function(d,b){d.exports=function(b,a,d){return b.on(a,d),{destroy:function(){b.removeListener(a,
d)}}}},function(d,b){var c=[].slice;d.exports=function(a,b){if("string"==typeof b&&(b=a[b]),"function"!=typeof b)throw Error("bind() requires a function");var d=c.call(arguments,2);return function(){return b.apply(a,d.concat(c.call(arguments)))}}},function(d,b){function c(a){a=a||{};this.ms=a.min||100;this.max=a.max||1E4;this.factor=a.factor||2;this.jitter=0<a.jitter&&1>=a.jitter?a.jitter:0;this.attempts=0}d.exports=c;c.prototype.duration=function(){var a=this.ms*Math.pow(this.factor,this.attempts++);
if(this.jitter){var b=Math.random(),c=Math.floor(b*this.jitter*a);a=0==(1&Math.floor(10*b))?a-c:a+c}return 0|Math.min(a,this.max)};c.prototype.reset=function(){this.attempts=0};c.prototype.setMin=function(a){this.ms=a};c.prototype.setMax=function(a){this.max=a};c.prototype.setJitter=function(a){this.jitter=a}}]);var Input$$module$src$input=function(){var d=this.keys={},b=this.keyCodes={};document.addEventListener("keydown",function(c){d[c.key]=b[c.keyCode]=!0});document.addEventListener("keyup",function(c){d[c.key]=b[c.keyCode]=!1})},module$src$input={};module$src$input.Input=Input$$module$src$input;var io$$module$src$io=module$node_modules$socket_io_client$dist$socket_io_slim["default"],room$$module$src$io=decodeQuery$$module$src$io(window.location.href).room||"default";console.log("room",room$$module$src$io);var connected$$module$src$io=!1,socket$$module$src$io=(0,module$node_modules$socket_io_client$dist$socket_io_slim["default"])("https://ess-server.herokuapp.com/api/little-game/no-persist-open-chat");
socket$$module$src$io.on("connect",function(){socket$$module$src$io.emit("init",{room:"default",nickname:module$src$game.getPlayer().from},function(){console.log("connected");connected$$module$src$io=!0;emit$$module$src$io(module$src$game.getPlayer())})});socket$$module$src$io.on("msg",function(d){console.log("msg",d);module$src$game.sync(d)});socket$$module$src$io.on("disconnect",function(){console.log("disconnected");connected$$module$src$io=!1});
var emit$$module$src$io=function(d){connected$$module$src$io&&(console.log("emit",d),socket$$module$src$io.emit("msg",d))};function decodeQuery$$module$src$io(d){d=d.split("?").slice(-1)[0].split("#")[0];for(var b={},c=d.split("&"),a=0;a<c.length;a++)d=c[a].split("="),b[decodeURIComponent(d[0])]=decodeURIComponent(d[1]);return b}var module$src$io={emit:emit$$module$src$io};var input$$module$src$game=new Input$$module$src$input,map$$module$src$game=[1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,0,1,0,0,1,1,1,1,1,1,1,0,0,1,1,1,1,1,1,0,0,1,1,1,1,1,1,1,1,1,1,1,1],gravity$$module$src$game=20,platformHeight$$module$src$game=12,mapDim$$module$src$game={width:8,height:6},scale$$module$src$game=100,pDim$$module$src$game={width:20,height:50},otherPlayers$$module$src$game={},canvas$$module$src$game=document.getElementById("platformer-canvas"),ctx$$module$src$game=canvas$$module$src$game.getContext("2d"),
fps$$module$src$game=50,xSpeed$$module$src$game=400,ySpeed$$module$src$game=1,ySpeedClamp$$module$src$game=500,jumpSpeed$$module$src$game=500,interval$$module$src$game=null,renders$$module$src$game=0,started$$module$src$game=!1,player$$module$src$game={pos:{x:30,y:platformHeight$$module$src$game},vy:0,from:Math.random().toString(36),color:"#"+Math.floor(16777215*Math.random()).toString(16)},mapPreRender$$module$src$game=function(){var d=document.createElement("canvas");d.width=canvas$$module$src$game.width;
d.height=canvas$$module$src$game.height;var b=d.getContext("2d");b.fillStyle="#333";for(var c=0;c<map$$module$src$game.length;c++){var a=c%mapDim$$module$src$game.width,f=Math.floor(c/mapDim$$module$src$game.width);map$$module$src$game[c]&&b.fillRect(a*scale$$module$src$game,f*scale$$module$src$game+scale$$module$src$game-platformHeight$$module$src$game,scale$$module$src$game,platformHeight$$module$src$game)}return d}(),getPlayer$$module$src$game=function(){return player$$module$src$game},start$$module$src$game=
function(){interval$$module$src$game&&clearInterval(interval$$module$src$game);player$$module$src$game.pos={x:30,y:platformHeight$$module$src$game};player$$module$src$game.vy=0;interval$$module$src$game=setInterval(function(){update$$module$src$game()},1E3/fps$$module$src$game);render$$module$src$game();module$src$io.emit(player$$module$src$game)},stop$$module$src$game=function(){interval$$module$src$game&&clearInterval(interval$$module$src$game)},sync$$module$src$game=function(d){otherPlayers$$module$src$game[d.from]=
d},grounded$$module$src$game=!1,prevGrounded1$$module$src$game=!1,prevGrounded2$$module$src$game=!1,lastX$$module$src$game=player$$module$src$game.pos.x,lastY$$module$src$game=player$$module$src$game.pos.y,x$$module$src$game,y$$module$src$game,xRight$$module$src$game,update$$module$src$game=function(){if(input$$module$src$game.keys.a||input$$module$src$game.keys.ArrowLeft)player$$module$src$game.pos.x-=xSpeed$$module$src$game/fps$$module$src$game;if(input$$module$src$game.keys.d||input$$module$src$game.keys.ArrowRight)player$$module$src$game.pos.x+=
xSpeed$$module$src$game/fps$$module$src$game;var d=!1;player$$module$src$game.vy-=gravity$$module$src$game;player$$module$src$game.pos.y+=ySpeed$$module$src$game/fps$$module$src$game*player$$module$src$game.vy;x$$module$src$game=player$$module$src$game.pos.x/scale$$module$src$game>>0;xRight$$module$src$game=(player$$module$src$game.pos.x+pDim$$module$src$game.width)/scale$$module$src$game>>0;y$$module$src$game=mapDim$$module$src$game.height-(player$$module$src$game.pos.y/scale$$module$src$game>>0)-
1;(map$$module$src$game[y$$module$src$game*mapDim$$module$src$game.width+x$$module$src$game]||map$$module$src$game[y$$module$src$game*mapDim$$module$src$game.width+xRight$$module$src$game])&&player$$module$src$game.pos.y%scale$$module$src$game<platformHeight$$module$src$game?(d=!0,0>player$$module$src$game.vy?(player$$module$src$game.vy=0,player$$module$src$game.pos.y=(player$$module$src$game.pos.y/scale$$module$src$game>>0)*scale$$module$src$game+platformHeight$$module$src$game):(player$$module$src$game.vy=
-Math.abs(player$$module$src$game.vy),player$$module$src$game.pos.y=(player$$module$src$game.pos.y/scale$$module$src$game>>0)*scale$$module$src$game+scale$$module$src$game-pDim$$module$src$game.height)):(map$$module$src$game[(y$$module$src$game-1)*mapDim$$module$src$game.width+x$$module$src$game]||map$$module$src$game[(y$$module$src$game-1)*mapDim$$module$src$game.width+xRight$$module$src$game])&&player$$module$src$game.pos.y%scale$$module$src$game>scale$$module$src$game-pDim$$module$src$game.height&&
(!map$$module$src$game[(y$$module$src$game-1)*mapDim$$module$src$game.width+x$$module$src$game]&&map$$module$src$game[(y$$module$src$game-1)*mapDim$$module$src$game.width+xRight$$module$src$game]?player$$module$src$game.pos.x=x$$module$src$game*scale$$module$src$game+scale$$module$src$game-pDim$$module$src$game.width-1E-6:map$$module$src$game[(y$$module$src$game-1)*mapDim$$module$src$game.width+x$$module$src$game]&&!map$$module$src$game[(y$$module$src$game-1)*mapDim$$module$src$game.width+xRight$$module$src$game]?
player$$module$src$game.pos.x=x$$module$src$game*scale$$module$src$game+scale$$module$src$game:0>player$$module$src$game.vy?(player$$module$src$game.vy=0,player$$module$src$game.pos.y=(player$$module$src$game.pos.y/scale$$module$src$game>>0)*scale$$module$src$game+platformHeight$$module$src$game):(player$$module$src$game.vy=-Math.abs(player$$module$src$game.vy),player$$module$src$game.pos.y=(player$$module$src$game.pos.y/scale$$module$src$game>>0)*scale$$module$src$game+scale$$module$src$game-pDim$$module$src$game.height));
input$$module$src$game.keys[" "]&&(d||prevGrounded1$$module$src$game||prevGrounded2$$module$src$game)&&(player$$module$src$game.vy+=jumpSpeed$$module$src$game);player$$module$src$game.vy=Math.min(ySpeedClamp$$module$src$game,Math.max(-ySpeedClamp$$module$src$game,player$$module$src$game.vy));player$$module$src$game.pos.x=Math.min(mapDim$$module$src$game.width*scale$$module$src$game-pDim$$module$src$game.width,Math.max(0,player$$module$src$game.pos.x));player$$module$src$game.pos.y+pDim$$module$src$game.height>
mapDim$$module$src$game.height*scale$$module$src$game&&(player$$module$src$game.vy=-Math.abs(player$$module$src$game.vy));prevGrounded2$$module$src$game=prevGrounded1$$module$src$game=d;if(player$$module$src$game.pos.x!==lastX$$module$src$game||player$$module$src$game.pos.y!==lastY$$module$src$game)started$$module$src$game=!0,module$src$io.emit(player$$module$src$game);lastX$$module$src$game=player$$module$src$game.pos.x;lastY$$module$src$game=player$$module$src$game.pos.y},render$$module$src$game=
function(){ctx$$module$src$game.clearRect(0,0,mapDim$$module$src$game.width*scale$$module$src$game,mapDim$$module$src$game.height*scale$$module$src$game);1E3>renders$$module$src$game&&(ctx$$module$src$game.save(),ctx$$module$src$game.beginPath(),ctx$$module$src$game.arc(player$$module$src$game.pos.x+.5*pDim$$module$src$game.width,mapDim$$module$src$game.height*scale$$module$src$game-player$$module$src$game.pos.y-.5*pDim$$module$src$game.height,renders$$module$src$game+100,0,2*Math.PI,!1),ctx$$module$src$game.clip());
ctx$$module$src$game.drawImage(mapPreRender$$module$src$game,0,0);for(var d in otherPlayers$$module$src$game){var b=otherPlayers$$module$src$game[d];ctx$$module$src$game.fillStyle=b.color;ctx$$module$src$game.fillRect(b.pos.x,mapDim$$module$src$game.height*scale$$module$src$game-b.pos.y-pDim$$module$src$game.height,pDim$$module$src$game.width,pDim$$module$src$game.height)}ctx$$module$src$game.fillStyle=player$$module$src$game.color;ctx$$module$src$game.fillRect(player$$module$src$game.pos.x,mapDim$$module$src$game.height*
scale$$module$src$game-player$$module$src$game.pos.y-pDim$$module$src$game.height,pDim$$module$src$game.width,pDim$$module$src$game.height);1E3>renders$$module$src$game&&(started$$module$src$game&&(renders$$module$src$game+=5),ctx$$module$src$game.restore(),started$$module$src$game||(ctx$$module$src$game.font="bold 60px Verdana",ctx$$module$src$game.fillText("Use the keyboard",50,250),ctx$$module$src$game.fillText("to play the game",60,330)));interval$$module$src$game&&requestAnimationFrame(render$$module$src$game)},
module$src$game={getPlayer:getPlayer$$module$src$game,start:start$$module$src$game,stop:stop$$module$src$game,sync:sync$$module$src$game};var Heap$$module$src$heaptree=function(){this.items=[]};Heap$$module$src$heaptree.prototype.seek=function(){return this.items[0]};var MaxHeap$$module$src$heaptree=function(d){Heap$$module$src$heaptree.call(this);this.selector=d};$jscomp.inherits(MaxHeap$$module$src$heaptree,Heap$$module$src$heaptree);
MaxHeap$$module$src$heaptree.prototype.push=function(d){var b=this.items.length;for(this.items.push(d);0<b&&this.selector(this.items[Math.floor((b+1)/2-1)])<this.selector(this.items[b]);)d=this.items[b],this.items[b]=this.items[Math.floor((b+1)/2-1)],this.items[Math.floor((b+1)/2-1)]=d,b=Math.floor((b+1)/2-1)};
MaxHeap$$module$src$heaptree.prototype.pop=function(){if(1>=this.items.length)return this.items.pop();var d=this.items[0];this.items[0]=this.items.pop();for(var b=0;;){var c=this.selector(this.items[2*(b+1)])>this.selector(this.items[2*(b+1)-1])?2*(b+1):2*(b+1)-1;if(this.selector(this.items[b])<this.selector(this.items[c])){var a=this.items[b];this.items[b]=this.items[c];this.items[c]=a;b=c}else break}return d};
MaxHeap$$module$src$heaptree.prototype["delete"]=function(d){d=this.items.indexOf(d);for(this.items[d]=this.items.pop();;){var b=this.selector(this.items[2*(d+1)])>this.selector(this.items[2*(d+1)-1])?2*(d+1):2*(d+1)-1;if(this.selector(this.items[d])<this.selector(this.items[b])){var c=this.items[d];this.items[d]=this.items[b];this.items[b]=c;d=b}else break}};MaxHeap$$module$src$heaptree.prototype.heapify=function(d){for(var b=0;b<d.length;b++)this.push(d[b])};
var MinHeap$$module$src$heaptree=function(d){Heap$$module$src$heaptree.call(this);this.selector=d};$jscomp.inherits(MinHeap$$module$src$heaptree,Heap$$module$src$heaptree);MinHeap$$module$src$heaptree.prototype.push=function(d){var b=this.items.length;for(this.items.push(d);0<b&&this.selector(this.items[Math.floor((b+1)/2-1)])>this.selector(this.items[b]);)d=this.items[b],this.items[b]=this.items[Math.floor((b+1)/2-1)],this.items[Math.floor((b+1)/2-1)]=d,b=Math.floor((b+1)/2-1)};
MinHeap$$module$src$heaptree.prototype.pop=function(){if(1>=this.items.length)return this.items.pop();var d=this.items[0];this.items[0]=this.items.pop();for(var b=0;;){var c=this.selector(this.items[2*(b+1)])<this.selector(this.items[2*(b+1)-1])?2*(b+1):2*(b+1)-1;if(this.selector(this.items[b])>this.selector(this.items[c])){var a=this.items[b];this.items[b]=this.items[c];this.items[c]=a;b=c}else break}return d};
MinHeap$$module$src$heaptree.prototype["delete"]=function(d){d=this.items.indexOf(d);for(this.items[d]=this.items.pop();;){var b=this.selector(this.items[2*(d+1)])<this.selector(this.items[2*(d+1)-1])?2*(d+1):2*(d+1)-1;if(this.selector(this.items[d])>this.selector(this.items[b])){var c=this.items[d];this.items[d]=this.items[b];this.items[b]=c;d=b}else break}};MinHeap$$module$src$heaptree.prototype.heapify=function(d){for(var b=0;b<d.length;b++)this.push(d[b])};var module$src$heaptree={};
module$src$heaptree.MaxHeap=MaxHeap$$module$src$heaptree;module$src$heaptree.MinHeap=MinHeap$$module$src$heaptree;module$src$game.start();var module$src$index={};var GridPath$$module$src$pathfinding=function(d,b){this.width=d;this.height=b;this.len=d*b;this.goalI=this.startI=null};
GridPath$$module$src$pathfinding.prototype.find=function(d,b,c){this.startI=d;this.goalI=b;var a={},f={},h={};h[d]=0;var k={},n=new MinHeap$$module$src$heaptree(function(a){return k[a]||Infinity});k[d]=this.heuristicCostEstimateSquared(d,b);for(n.push(d);0<n.items.length;){d=n.pop();if(d===b)return this.reconstructPath(f,d);a[d]=!0;for(var l=this.neighboursI(d),p=0;p<l.length;p++){var m=l[p];if(!(0>m||m>this.len||a[m]||c&&!c(m))){var q=h[d]+1;k[m]?q>=h[m]||(f[m]=d,h[m]=q,k[m]=q+this.heuristicCostEstimateSquared(m,
b),n["delete"](m),n.push(m)):(f[m]=d,h[m]=q,k[m]=q+this.heuristicCostEstimateSquared(m,b),n.push(m))}}}};GridPath$$module$src$pathfinding.prototype.reconstructPath=function(d,b){var c=0,a=[];for(a.push(b);b!==this.startI;)if(a.push(b),b=d[b],999999<c++)return null;a.push(this.startI);c=Array(a.length);for(var f=0;f<a.length;f++)c[f]=a[a.length-1-f];return c};GridPath$$module$src$pathfinding.prototype.neighboursI=function(d){return[d-this.width,d+1,d+this.width,d-1]};
GridPath$$module$src$pathfinding.prototype.heuristicCostEstimateSquared=function(d,b){return Math.pow(b%this.width-d%this.width,2)+Math.pow(Math.floor(b/this.width)-Math.floor(d/this.width),2)};var module$src$pathfinding={};module$src$pathfinding.GridPath=GridPath$$module$src$pathfinding;
}).call(this)
